### DISCUSSION TITLE
Applicationset based on public helm repos, and different values per cluster.

### DISCUSSION THREAD

**Discussion by marcportabellaclotet-mt** [argoproj-labs/applicationset#298] [General]
I would like to use applicationset to install cluster addons. For example prometheus-operator, keda, argo-rollouts...

Reading the provided [examples](https://github.com/argoproj-labs/applicationset/tree/master/examples/git-generator-directory/cluster-addons/prometheus-operator), it uses requirements to load external helm charts.

As this is not using kustomization, how can I define a different values per each cluster?

When running helm or argoproj.io/v1alpha1 | Application, you can define multiple helm files:
```
 targetRevision: HEAD
    helm:
      version: v3
      releaseName: rollouts-demo
      valueFiles:
      - values.yaml
      - values-test.yaml
  ``` 

Using [template overrides](https://github.com/argoproj-labs/applicationset/tree/master/examples/template-override), you need to have a copy or simlink of the Chart.yaml ,requirements.yaml per override, and a specific values.yaml.

My goal is to use public helms, and set diffrent values.yaml per cluster. Also allowing multiple values.yaml would be great.

Maybe I am missing something, and this can be achieved somehow.

Thanks in advance.
