### DISCUSSION TITLE
ApplicationSet controller is not creating Applications from list of clusters

### DISCUSSION THREAD

**Discussion by tahirali-endurance** [argoproj-labs/applicationset#395] [Q&A] [answered]
We are following this article(https://argocd-applicationset.readthedocs.io/en/stable/#the-applicationset-resource)) for rendering ApplicationSet for multiple clusters, but Application manifest is not rendered.

```
argocd version: quay.io/argoproj/argocd:v2.1.5  
applicationset-controller: quay.io/argoproj/argocd-applicationset:v0.2.0
```

This is how our ApplicationSet manifest looks like:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://1.2.3.4
      - cluster: engineering-prod
        url: https://2.4.6.8
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.roving.com/ES/poc-cluster-deployments.git
        targetRevision: HEAD
        path: guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
```

It appears that ApplicatonSetController is not watching the ApplicationSet resources. Any ideas?
