### DISCUSSION TITLE
How to template syncPolicy options from config

### DISCUSSION THREAD

**Discussion by ibiqlik** [argoproj-labs/applicationset#414] [Q&A]
How do I template syncPolicy based on the `config.yaml|json` values?
For example I want to individually set syncPolicy for each app by setting the settings in the `path/app/config.yaml` which is monitored by applicationset

```yaml
syncPolicy:
  automated:
    selfHeal: true
```

Or completely disable it on some apps

```yaml
syncPolicy: {}
```

I tried the following but obviously it doesn't work 

```yaml
spec:
  template:
    spec:
      syncPolicy: { '{{syncPolicy}}' }
```
