### DISCUSSION TITLE
Matrix generator with multiple git generators.

### DISCUSSION THREAD

**Discussion by AmrAlaaYassen** [argoproj-labs/applicationset#448] [Q&A]
Hello all,
when I tried to create a matrix generator with multiple git generators, I get an error telling me that I got the same key with multiple values.
is there a way to create multiple git generators using a matrix generator, or use a different key than the path key to populate different values? 

so I want something like this
```yaml apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL:  <REPO_URL>
              revision: HEAD
              directories:
                - path: dir1/*
           - git:
              repoURL: <REPO_URL>
              revision: HEAD
              directories:
                - path: dir2/*
  template: 
```
thanks,
