### DISCUSSION TITLE
Unable to create Helm Application for Git ApplicationSet

### DISCUSSION THREAD

**Discussion by knure** [argoproj-labs/applicationset#461] [Q&A]
I've created, what I believe should deploy all appliactions found in a Git repo... But Argocd happliy claims it sattisfied with only creating an Argocd Application, without ever creating any pods. I
What Am I doing wrong? I'm running Argocd Operator 0.10 on OCP4 with Argocd v.2.2.2.

**Top Application**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-set-test-hello-world
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: ssh://git@bitbucket.xyz.se:7999/team-cicd/deploy-hello-world.git
    targetRevision: HEAD
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
```

**Top App calls this one ....**
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-example
spec:
  generators:
  - git:
      repoURL: ssh://git@bitbucket.xyz.se:7999/team-cicd/hello-world.git
      revision: HEAD
      directories:
      - path: ./*
      # - path: charts/*
#      - path: charts/hello-world/*
  template:
    metadata:
      name: applicationset-hello-world
    spec:
      project: default
      source:
        repoURL: ssh://git@bitbucket.xyz.se:7999/team-cicd/hello-world.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - 'values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated: {}
```

**Hello world is the standard Helm Hello World found at https://helm.github.io/examples**

The log only tells me that:

```
time="2022-01-14T09:10:38Z" level=info msg="Skipping auto-sync: application status is Synced" application=app-set-test-hello-world
time="2022-01-14T09:10:38Z" level=info msg="Update successful" application=app-set-test-hello-world
time="2022-01-14T09:10:38Z" level=info msg="Reconciliation completed" application=app-set-test-hello-world dedup_ms=0 dest-name= dest-namespace=argocd dest-server=https://kubernetes.default.svc diff_ms=1 fields.level=2 git_ms=17 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=345
```

What have I missed??
