### DISCUSSION TITLE
Clusters with many different tenants

### DISCUSSION THREAD

**Discussion by mannro** [argoproj-labs/applicationset#485] [Q&A]
We have clusters with many different tenant namespaces. How can i generate tenant deployments per cluster?

- cluster1.config.yaml
```
cluster:
  name: dev
  server: https://kubernetes.default.svc
  tenants:
    - name: dev
      id: 1
    - name: tenant.dev.123
      id: 2
    - ...
```
- cluster2.config.yaml
```
cluster:
  name: testing
  server: ...
  tenants:
    - name: test
      id: 1
    - name: tenant.test.456
      id: 2
    - ...
```

desired applications:
- cluster1.dev
- cluster1.tenant.dev.123
- cluster1.tenant....
- cluster2.test
- cluster2.tenant.test.456
- cluster2.tenant
- ...
