### DISCUSSION TITLE
Support diffing of Applications generated from ApplicationSet

### DISCUSSION THREAD

**Discussion by agaudreault** [argoproj-labs/applicationset#542] [Ideas]
I am trying to use the `RespectIgnoreDifferences` feature of ArgoCD 2.3.0 with `managedFieldsManagers: [argocd-server]` to ignores changes to my application `.spec.syncPolicy.automated` so I can disable automated sync in the UI/CLI without changing the manifest defined as code.

It seems like it will not work for Application created from ApplicationSet when I am reading the [documentation](https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#limitation-applicationset-controller-will-not-selectively-ignore-changes-to-individual-fields). 
Docs says discussions are in progress on slack/github, but I could not find any.

This would not work.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'example.{{name}}'
    spec:
      destination:
        namespace: example
        name: '{{name}}'
      project: default
      source:
        path: apps/example
        repoURL: https://github.com/user/repo
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
        - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          managedFieldsManagers:
            - argocd-server
          jsonPointers:
            - /spec/syncPolicy/automated
```

But using the Application directly, it would work
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
spec:
  destination:
    namespace: example
    name: in-cluster
  project: default
  source:
    path: apps/example
    repoURL: https://github.com/user/repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      managedFieldsManagers:
        - argocd-server
      jsonPointers:
        - /spec/syncPolicy/automated
```
