### DISCUSSION TITLE
Appset is not spawning applications.

### DISCUSSION THREAD

**Discussion by vra5107** [argoproj-labs/applicationset#563] [Q&A]
For some reason my `app of appset` setup is not spawning applications.  Have spent quite a bit of time on this, not sure what I am doing wrong. already went through some of the other issues posted here without success.

I have tried applying the appset.yaml directly instead of the `app of appset` setup. I had no success that way either.

### Root App

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acquisition-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: appsets
    repoURL: https://github.com/internal/gitops-envconfig.git
    targetRevision: fromdevelop
```

### Appset

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acquisition
spec:
  generators:
  - git:
      repoURL: https://github.com/internal/gitops-envconfig.git
      revision: fromdevelop
      directories:
      - path: fromdevelop/argocd-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/internal/gitops-envconfig.git
        targetRevision: fromdevelop
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
```

Application.yaml
There are application yaml files at `fromdevelop/argocd-apps/`

### Image of the UI
I can see that the ArgoCD shows both the root app and appset. But it doesn't spawn the applications declared at `fromdevelop/argocd-apps/`

![image](https://user-images.githubusercontent.com/122128/160287412-78d5afa7-7c25-45cd-881d-18be487651fd.png)

### LOG

Even in the debug mode, the logs aren't telling me anything.

>   $ kubectl -n argocd logs -f argocd-applicationset-controller-64bf887cf-fbvsh
> 1.6483915909900901e+09  INFO    setup   ApplicationSet controller v0.4.1 using namespace 'argocd'       {"namespace": "argocd", "COMMIT_ID": "a5712ba564afaff0b23697135d6281
> d413e60345"}
> 1.6483915917958052e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
> time="2022-03-27T14:33:11Z" level=info msg="Starting configmap/secret informers"
> time="2022-03-27T14:33:11Z" level=info msg="Configmap/secret informer synced"
> 1.6483915919047391e+09  INFO    setup   Starting manager
> 1.6483915919049582e+09  INFO    setup   Starting webhook server
> 1.6483915919060104e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
> 1.648391591906014e+09   INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
> 1.6483915920068798e+09  INFO    controller.applicationset       Starting EventSource    {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "source": "
> kind source: *v1alpha1.ApplicationSet"}
> 1.6483915920070128e+09  INFO    controller.applicationset       Starting EventSource    {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "source": "
> kind source: *v1alpha1.Application"}
> 1.64839159200703e+09    INFO    controller.applicationset       Starting EventSource    {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "source": "
> kind source: *v1.Secret"}
> 1.6483915920070388e+09  INFO    controller.applicationset       Starting Controller     {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet"}
> 1.6483915921089263e+09  INFO    controller.applicationset       Starting workers        {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "worker cou
> nt": 1}
> time="2022-03-27T14:33:12Z" level=debug msg="https://github.com/internal/gitops-envconfig.git has credentials"
> time="2022-03-27T14:33:12Z" level=info msg="Initializing https://github.com/internal/gitops-envconfig.git to /tmp/https___github.com_internal_gitops-envconfig"
> time="2022-03-27T14:33:12Z" level=info msg="rm -rf /tmp/https___github.com_internal_gitops-envconfig" dir= execID=cfef2
> time="2022-03-27T14:33:12Z" level=debug duration=1.356226ms execID=cfef2
> time="2022-03-27T14:33:12Z" level=info msg=Trace args="[rm -rf /tmp/https___github.com_internal_gitops-envconfig]" dir= operation_name="exec rm" time_ms=2.669151
> time="2022-03-27T14:33:12Z" level=info msg="git fetch origin fromdevelop --tags --force" dir=/tmp/https___github.com_internal_gitops-envconfig execID=66a31
> time="2022-03-27T14:33:13Z" level=debug duration=914.492658ms execID=66a31
> time="2022-03-27T14:33:13Z" level=info msg=Trace args="[git fetch origin fromdevelop --tags --force]" dir=/tmp/https___github.com_internal_gitops-envconfig operation_na
> me="exec git" time_ms=914.6055600000001
> time="2022-03-27T14:33:13Z" level=debug msg="revision 'fromdevelop' resolved to '394b48b10b160dbee93d2dba10e1d2ed19df27bd'"
> time="2022-03-27T14:33:13Z" level=info msg="git checkout --force 394b48b10b160dbee93d2dba10e1d2ed19df27bd" dir=/tmp/https___github.com_internal_gitops-envconfig execID=
> a32df
> time="2022-03-27T14:33:13Z" level=debug duration=10.559301ms execID=a32df
> time="2022-03-27T14:33:13Z" level=info msg=Trace args="[git checkout --force 394b48b10b160dbee93d2dba10e1d2ed19df27bd]" dir=/tmp/https___github.com_internal_gitops-envc
> onfig operation_name="exec git" time_ms=10.657903
> time="2022-03-27T14:33:13Z" level=info msg="git clean -fdx" dir=/tmp/https___github.com_internal_gitops-envconfig execID=7bdfc
> time="2022-03-27T14:33:13Z" level=debug duration=2.702051ms execID=7bdfc
> time="2022-03-27T14:33:13Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_-internal_gitops-envconfig operation_name="exec git" time_ms=2.80435
> 3
> time="2022-03-27T14:33:13Z" level=info msg="applications result from the repo service" allPaths="[appsets cicd fromdevelop fromdevelop/apps fromdevelop/apps/online-enrollme
> nt-reactive fromdevelop/apps/online-enrollment-reactive/helm fromdevelop/apps/online-enrollment-reactive/k8s fromdevelop/apps/online-enrollment-reactive/k8s/base fromdevelo
> p/apps/online-enrollment-reactive/k8s/overlays fromdevelop/argocd-apps fromdevelop/cr-manifests prerelease release release-lifecycle-phase-argocd-apps uml]" repoURL="https:
> //github.com/internal/gitops-envconfig.git" revision=fromdevelop total=15
> time="2022-03-27T14:33:13Z" level=info msg="generated 0 applications" generator="{<nil> <nil> 0xc000841380 <nil> <nil> <nil> <nil> <nil>}"
> time="2022-03-27T14:33:13Z" level=debug msg="apps from generator: []" generator="{<nil> <nil> 0xc000841380 <nil> <nil> <nil> <nil> <nil>}"
> time="2022-03-27T14:33:13Z" level=info msg="end reconcile" requeueAfter=3m0s
> time="2022-03-27T14:36:13Z" level=debug msg="https://github.com/internal/gitops-envconfig.git has credentials"
> time="2022-03-27T14:36:13Z" level=info msg="git fetch origin fromdevelop --tags --force" dir=/tmp/https___github.com_internal_gitops-envconfig execID=6cd59
> time="2022-03-27T14:36:13Z" level=debug duration=525.544868ms execID=6cd59
> time="2022-03-27T14:36:13Z" level=info msg=Trace args="[git fetch origin fromdevelop --tags --force]" dir=/tmp/https___github.com_internal_gitops-envconfig operation_na
> me="exec git" time_ms=525.756173
> time="2022-03-27T14:36:14Z" level=debug msg="revision 'fromdevelop' resolved to '394b48b10b160dbee93d2dba10e1d2ed19df27bd'"
> time="2022-03-27T14:36:14Z" level=info msg="git checkout --force 394b48b10b160dbee93d2dba10e1d2ed19df27bd" dir=/tmp/https___github.com_internal_gitops-envconfig execID=
> 804a8
>
