### DISCUSSION TITLE
How to pass empty array [] to Helm value

### DISCUSSION THREAD

**Discussion by Dentrax** [argoproj-labs/applicationset#591] [Q&A]
My `values.yaml`:

```yaml
config:
  resourceFilters: []
```

My `appset.yaml`

```yaml
...
source:
    helm:
      parameters:
      - name: foo.bar
        value: "[]"           
```

What is the correct representation of passing empty array `[]` in `source.helm.parameters.value`?
