### DISCUSSION TITLE
ApplicationSet merge generator - git files

### DISCUSSION THREAD

**Discussion by ghost** [argoproj-labs/applicationset#603] [Q&A]
Hi :)
I'm trying to create kind of hierarchy values, here is the applicationset code:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-app-dynamic-cluster
spec:
  generators:
    - merge:
        mergeKeys:
          - path[1]
        generators:
          - git:
              repoURL: https://bitbucket.org/team/argocd
              revision: master
              files:
                - path: 'clusters/*/values.yaml'
          - git:
              repoURL: https://bitbucket.org/team/argocd
              revision: master
              files:
                - path: 'clusters/*/*/helm/*/values.yaml' # cluster/<cluster>/<namespace>/helm/<releaseName>
```

ERROR: `the parameters from a generator were not unique by the given mergeKeys, Merge requires all param sets to be unique. Duplicate key was {\"path\[1\]\":\"\"}"`

I would like to merge the parameters in values.yaml configurations by the cluster name (path[1]) and generate an Application for each releaseName, what am I missing with the merge generator?
