### DISCUSSION TITLE
Applicationset - is it possible to generate an applicationset only if the path exists?

### DISCUSSION THREAD

**Discussion by v4mpir0ck** [argoproj-labs/applicationset#629] [Q&A]
Hi!
im triyng to create an aplicationset that uses a matrix with list + git generator.
We have different providers (eks and ocp) and several environments.
With all of these, im to generating a folder with the structure /<environment>/<provider>/

My question is, ¿is it possible any way to create the appsets, only if exists the folder?

example of the folder:
my git folder > INT
--------------------> EKS
--------------------> OCP
                      PRE
--------------------> EKS
                          
The applicationset yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements: 
                - prov: eks
                - prov: ocp
          - git:
              repoURL: http://my-internal-server
              revision: master
              directories:
              - path: '*' 
  template:
    metadata:
      name: '{{path.basename}}-{{prov}}-myapp'
    spec:
      project: 'default'
      source:
        repoURL: http://my-internal-server
        targetRevision: master
        path: '{{path}}/providers/{{prov}}'
      destination:
        server: https://kubernetes.default.svc # se podria hacer con una busqueda de clusters y seleccionar los metadata.server 
        namespace: 'argocd-apps-{{path.basename}}-{{prov}}'
```

this should create 3 apps
INT-EKS-myapp
INT-OCP-myapp
PRE-EKS-myapp
                 
but with this code, also creates the PRE-OCP-myapp (creating confusión), can we ignore the empty folder, or just instanyiate the appset only if the folder exists?

thank you!
