### DISCUSSION TITLE
Generator template override with multi source

### DISCUSSION THREAD

**Discussion by Guitarkalle** [argoproj-labs/applicationset#637] [Q&A]
Hello,

I have a applicationset with two git generators. Both of these specify a template override to replace something in the source spec.
The problem is that I use multi source, which is a list. How can I target a specific element in the source list from the generator template override section? Will it by default pick the first element in the list to merge into?

An example:

```

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
        - name: 'appWithPath'
           path: 'test'
           ....
      template:
        spec:
          sources:
          -  path: '{{path}}'
  - list:
      elements:
        - name: 'AppWithChart' 
           chart: 'test'
           ....
      template:
        spec:
          sources:
          - chart: '{{chart}}'
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: "default"
      sources:
      -  repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          # inject generator template path into this source here
      - ... Another source here ... 
      destination:
        server: 'in-cluster'
        namespace: guestbook

```
