### ISSUE TITLE
Method for overriding resource deletion default behavior

### ISSUE THREAD

**Issue by jbaskeen** [argoproj-labs/applicationset#103]
Currently, the AppSet spec enforces deletion of related Applications and their deployed resources by default. This is not consistent with the default behavior of Application in argo-cd. That is, without AppSets, deployed resources related to an Application are not deleted by default when an Application is deleted. This situation presents a rather confusing situation for users of Application _and_ ApplicationSet since their default behavior for resource deletion has diverged.

Proposal

- Allow for a method to set the default behavior of ApplicationSet to not delete resources when an ApplicationSet is deleted. A runtime flag would be a possible solution to set the desired default behavior.
- Allow for the controller's default behavior to be overridden or set within the ApplicationSet spec via an attribute setting.

Justification

In some cases, critical infrastructure resources or applications may be synced to a cluster using ApplicationSet which need to be "protected" from deletion in case of human error in ArgoCD configurations. In the event that an unintentional deletion, by whatever means, of AppSets, or Applications that are linked to AppSets, a Production environment state could be lost causing an outage of provided services. This exact scenario occurred on my team where an inappropriate Argo configuration caused deletion of our AppSets resulting in all environments to be wiped clean by Argo. This occurred because of the default behavior of ApplicationSet with respect to deletions and we did not expect that behavior (we expected the same behavior as Application) as a result of our lack of due diligence prior to Production usage. In this specific case, persistent storage which was provisioned via Argo was also lost. In the case of storage, as a sensitive asset type, it is reasonable to expect a way of protecting those resources from erroneous deletion because of their stateful nature.

**Comment by jgwest** [comment]
@jbaskeen has provided an excellent description of why this is a valid use case, and I am personally convinced that we should allow users to customize this behaviour if they wish (eg as a supported behaviour). 

#### Re: changing the default behaviour

IMHO the current default for ApplicationSet is the correct default: ApplicationSet is meant to be an abstraction over Argo CD `Application` resources, with the user managing `ApplicationSet` resources directly, and the ApplicationSet controller handling changes to the corresponding `Application`s behind the scenes.

Thus, to preserve that abstraction as much as possible, the lifecycle of the ApplicationSet, of the Application, and of the Application resources, should be equal. Eg when the ApplicationSet is deleted, so is the Application, and so are the Application's resources. 

(Likewise, I would note that Argo CD doesn't have a consistent default here: for example, the web UI and the CLI both use cascade deletion by default)

#### Proposal

But, as above, users that are fully aware of the consequences should totally be able to do this (and, for example, in a related function, we already support customization of default behaviour via the `--policy` param to the controller).

My suggestion would be something like this, adding a new field to `syncPolicy` to control this behaviour:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: guestbook
spec:
 generators:
 - list:
     elements:
     - cluster: engineering-dev
       url: https://kubernetes.default.svc
 template:
   metadata:
     name: '{{cluster}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/jgwest/argocd-example-apps.git
       targetRevision: HEAD
       path: appset-examples/list-examples/guestbook/{{cluster}}
     destination:
       server: '{{url}}'
       namespace: guestbook
  syncPolicy:
    preserveResourcesOnDeletion: true # <------ new field, defaults to false if not specified
```

If `preserveResourcesOnDeletion` (*anyone have a better name for the field?*) is true, then when you delete an `Application` created by an `ApplicationSet`, the child resources of the Application will be preserved.

Specifically, behind the scenes, if `preserveResourcesOnDeletion` is true, it would not add the `resources-finalizer.argocd.argoproj.io` finalizer [here](https://github.com/argoproj-labs/applicationset/blob/b6ac04b7108720e273d9cc6bdfc313a592bddc02/pkg/utils/util.go#L50) to the created `Application` resources.

Since this is a field on `syncPolicy` on a single ApplicationSet (rather than being a global controller-wide flag), one can customize which ApplicationSets use this behaviour.

Does this sound reasonable?

**Comment by ygelfand** [comment]
One slight caveat to this (and how we've done it internally for now) is to handle it w/ parameters to the generator, vs a global application set parameter.  This allows you to for instance target "dev" clusters w/ preserveResourcesOnDeletion: false, vs prod clusters w/ preserveResourcesOnDeletion: true.   Handling it via values in the generator currently (admittedly that's a bit hacky), but does provide this level of separation.

**Comment by jbaskeen** [comment]
Given the purpose of cluster generators, and scoping to these different contexts, I totally agree with @ygelfand. Allowing for Prod contexts to be protected but allowing deletion in other contexts fits our use case perfectly. @jgwest thoughts?

**Comment by jgwest** [comment]
Excellent question... now that https://github.com/argoproj-labs/applicationset/pull/91 has merged, and with the `preserveResourcesOnDeletion` field I mentioned above, you should be able to do something like this in order to support that use case:
   
```yaml
# Simple ApplicationSet Example
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: guestbook
spec:
 generators:
 - list:
     elements:
     - cluster: engineering-dev
       url: https://kubernetes.default.svc
       values:
         preserve: false # <----- custom key/value parameter, which will be turned into a values.preserve param
     - cluster: engineering-prod
       url: https://kubernetes.default.svc
       values:
         preserve: true  # <----- as above
         
 template:
   metadata:
     name: '{{cluster}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/jgwest/argocd-example-apps.git
       targetRevision: HEAD
       path: appset-examples/list-examples/guestbook/{{cluster}}
     destination:
       server: '{{url}}'
       namespace: guestbook
  syncPolicy:
    preserveResourcesOnDeletion: {{values.preserve}} # <------ takes value from generated parameter of cluster generator
```
