### ISSUE TITLE
Support custom keys in ListGeneratorElement

### ISSUE THREAD

**Issue by maruina** [argoproj-labs/applicationset#108]
Hi all,
I was wondering if you where open to a PR to extend the `ListGeneratorElement` to support additional key other than `cluster` and `url`. Something like to
```
type ListGeneratorElement struct {
	Cluster string `json:"cluster"`
	Url     string `json:"url"`
	Labels  map[string]string `json:"labels,omitempty"`
}
```

Happy to discuss the `Labels name`, it was the first thing that came to my mind.

My use case is that I need to inject some parameters per cluster, and what I have at the moment is

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-helm-dep
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: eu-west-1a-1
          url: "https://eu-west-1a-1-control-plane:6443"
        - cluster: eu-west-1b-1
          url: "https://eu-west-1b-1-control-plane:6443"
        - cluster: eu-central-1a-1
          url: "https://eu-central-1a-1-control-plane:6443"
  template:
    metadata:
      name: '{{cluster}}-helm-dep'
    spec:
      project: default
      source:
        repoURL: https://github.com/maruina/appset-poc.git
        targetRevision: HEAD
        path: goinfra
        helm:
          releaseName: goinfra
          valueFiles:
            - "values.yaml"
            - "values-{{cluster}}.yaml"
```
but if the `"values-{{cluster}}.yaml"` doesn't exist the Application will fail. I'd like to set the per-cluster values from the generator as parameters and just have a common `values.yaml`.

I'm happy to raise a PR for this work.

**Comment by jgwest** [comment]
Hi @maruina, it looks like what you are asking for is similar to what @mgoodness added with https://github.com/argoproj-labs/applicationset/pull/91 for the Cluster generator.

So if we were to add the same thing for list generator, I expect it would look like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-helm-dep
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: eu-west-1a-1
          url: "https://eu-west-1a-1-control-plane:6443"
          values:
            version: '2.0.0'          
        - cluster: eu-west-1b-1
          url: "https://eu-west-1b-1-control-plane:6443"
          values:
            version: '2.0.0' # <------         
        - cluster: eu-central-1a-1
          url: "https://eu-central-1a-1-control-plane:6443"
          values:
            version: '2.0.0' # <------
          
  template:
    metadata:
      name: '{{cluster}}-helm-dep'
    spec:
      project: default
      source:
        repoURL: https://github.com/maruina/appset-poc.git
        targetRevision: HEAD
        path: goinfra
        helm:
          releaseName: goinfra
          parameters:
            - name: version
              value: {{ values.version }}  # <---- values from the list have the 'values.' prefix to prevent name clashes
          valueFiles:
            - "values.yaml"
            - "values-{{cluster}}.yaml"
```

Was that about what you were expecting? (I used version as an arbitrary key here, but of course it could be anything). The [filters example](https://github.com/argoproj-labs/applicationset/blob/master/examples/filters.yaml) gives an example of how this works for the cluster generator.
