### ISSUE TITLE
RenderTemplateParams allows templates with unresolved parameters, without warning

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#122]
Blocked on https://github.com/argoproj-labs/applicationset/issues/71

`RenderTemplateParams`, the function responsible for rendering templates into `Application`s, currently does not throw an error if a parameter cannot be found.

For example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{param-does-not-exist}}-guestbook'   # <--- this parameter does not exist
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: guestbook
```
In this case, the `param-does-not-exist` parameter is not contributed by the generator. But, `RenderTemplateParams` does not throw an error in this case, rather it just leaves the template field as is. So you will get an Argo CD Application with ` {{param-does-not-exist}}` field within the metadata.

Once #71 is implemented, we should include an error message under `status` in the `ApplicationSet` CRD for this. In the mean time, it's probably best to leave the behaviour as is: unparameterized fields will always be invalid no matter where the occur, so there's probably no risk of data corruption or outages. 

If a user wants to know why their Application is invalid, they can manually inspect the failing Applications, and will see the unparameterized value, and can fix the ApplicationSet.
