### ISSUE TITLE
annotations set in application-set not updating apps 

### ISSUE THREAD

**Issue by mr-sour** [argoproj-labs/applicationset#154]
```
  template:
    metadata:
      annotations:
        argocd.argoproj.io/manifest-generate-paths: consul/consul-agent
```
With application annotations it will create the annotation correctly but if you try to modify it the changes dont sync unless you delete the application and regenerate. Pretty easy to test, create a annotation like above and then try changing it.
