### ISSUE TITLE
Parameterized template overrides 

### ISSUE THREAD

**Issue by mr-sour** [argoproj-labs/applicationset#157]
I'm unsure if this is a bug, feature request, not supported or I'm just doing it wrong.

Using the list generator I want to set the targetRevision on a per-cluster basis as to slowly roll changes but have it fall back if not specified.  What I was trying to attempt is if values.targetRevision exists for a certain cluster it would override the value at `spec.template.spec.source.targetRevision`  with `spec.generators.source.targetRevision`. What really happens is if a cluster doesn't have values.targetRevision the target revision gets set to  "{{values.targetRevision}}" when what I want to happen is for it to get set to the value at spec.template.spec.source.targetRevision. 

For now I have just included a values.targetRevision for everything in the list and if this isn't a supported use case I'll just leave it like that. Its not a deal breaker by any means I'm just curious if there way to accomplish this.

![image](https://user-images.githubusercontent.com/2181180/111231817-e3a9d680-85b7-11eb-8823-68adaf82a18a.png)

Example manifest 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: override-test
spec:
  generators:
  - list:
      elements:
      - cluster: test
        url: local.test
        values:
          targetRevision: DEADBEEF #get set to DEADBEEF
      - cluster: test2 #gets set to {{values.targetRevision}}
        url: local.test
      template:
        metadata: {}
        spec:
          destination: {}
          project: default
          source:
            repoURL: my-best-work.git
            targetRevision: '{{values.targetRevision}}'
  template:
    metadata:
      labels:
      name: test-{{cluster}}
    spec:
      destination:
        namespace: test
        server: '{{url}}'
      project: default
      source:
        path: test
        repoURL: my-best-work.git
        targetRevision: HEAD 

```
