### ISSUE TITLE
Feature request: Duck Type Generator

### ISSUE THREAD

**Issue by jnpacker** [argoproj-labs/applicationset#158]
Hi,

This work on ApplicationSet's has sparked a bunch of ideas for me around Cluster Targeting.  I also see #114 is touching on this area as well.  It would be great to be able to leverage another resource as the generator. This way other tools could be incorporated or you could create your own matching algorithms.
```yaml
spec:
  generators:
  - generatorRef: my-list-resource
    generatorApiGroup: my-group.io/v1beta1
```
Kubernetes has the [Duck Type](https://github.com/knative/pkg/blob/main/apis/duck/README.md) concept for just this type of referencing.  Where a `status` contract would be written, and as long as your resource honored that contract, ApplicationSet would be able to read the cluster targeting from it.

## Example 1
Create a custom resource that generates the contract list based on anti-affinity rules for a cluster.
Consider four clusters:
* cluster1   # Region 1, `metadata.labels.region: apac
* cluster2   # Region 1, `metadata.labels.region: apac`
* cluster3   # Region 2, `metadata.labels.region: emea`
* cluster4   # Region 2, `metadata.labels.region: emea`

```yaml
---
apiVersion: v1alpha1
kind: MyOwnGenerator
metadata:
  name: my-target-clusters
spec:
  anti-affinity:
  - apac
  - emea
status:
  decisions:
  - cluster1  # Region apac
  - cluster3  # Region emea
```
ApplicationSets reading the contracted status.decisions will deploy an application to the two regions.  For a more advanced MyOwnGenerator, we might choose to detect cluster failures or networking issues, and adjust our `decision` based on availability.  

## Example 2
Create a custom resource that generates the contract list based on utilization of the cluster.
```yaml
---
apiVersion: v1alpha1
kind: MyOwnGenerator2
metadata:
  name: my-target-clusters2
spec:
  cluster-cpu-utilization: 80    # Percentage utilization
  resources-available: true
status:
  decisions:
  - cluster6
```
The controller evaluating the custom resource could make contracted decisions based on CPU utilization or based on available resource to RUN the app.  

This approach opens up many integration possibilities, allowing for powerful deployment scenarios.
