### ISSUE TITLE
List generator should allow any key/value pair

### ISSUE THREAD

**Issue by moises-perez-tfs** [argoproj-labs/applicationset#162]
I find cluster `name` to be a more readable options than `url` for referencing clusters in an Application (or ApplicationSet).

For example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: guestbook
spec:
 generators:
 - list:
     elements:
     - cluster: engineering-dev
       url: REQUIRED_BUT_NOT_USED
     - cluster: engineering-prod
       url: REQUIRED_BUT_NOT_USED
 template:
   metadata:
     name: '{{cluster}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/argoproj-labs/applicationset.git
       targetRevision: HEAD
       path: examples/list-generator/guestbook/{{cluster}}
     destination:
       name: '{{cluster}}'
       namespace: guestbook
```

This example works fine when setting the appropriate cluster names but it requires us to set an unused `url` parameter for each element. This parameter is never used in the `template` above. I think using the cluster `name` in `destination` and avoiding URLs would be much easier to read.

If https://github.com/argoproj-labs/applicationset/issues/158 is ever implemented, that could be used as an alternative.
