### ISSUE TITLE
Enhancement - Conditional plugin support

### ISSUE THREAD

**Issue by rbkaspr** [argoproj-labs/applicationset#168]
# What's the issue?
For some organizations, a monorepo of application manifests can contain a mix of different deployment mechanisms, especially when different teams with different preferences for things like Helm/Kustomize/etc are handling different deployments. If each of those deployments uses a standard structure that Argo natively understands, ApplicationSets can handle that with no issue.

However, if some of those manifests require special deployment logic (kustomized-helm, for example), the current ApplicationSet generators are basically all-or-nothing deals, mainly because of the fact that pluginSpec is a map and an ApplicationSpec can't just contain a name field with an empty string (otherwise this could be handled by setting or not setting a `plugin` value in settings file if we were using the git file generator.

## (Potential) Solution: Allow maps to be substituted
The current git file generator only seems to support substituting values as strings, adding map support could address this use case (and potentially others down the line)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      revision: HEAD
      files:
      - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: HEAD
        path: "examples/git-generator-files-discovery/apps/guestbook"
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
        '{{ plugin }}'
```
If we want to include a plugin, we add this to our config.json for a given app
```json
{
  "plugin": {
    "name": "kustomized-helm"
  }
}
```

If not, we either explicitly set plugin to be empty `{}`, or else omit the key, and the generator can just drop the plugin field from the generated ApplicationSpec
