### ISSUE TITLE
Use of `{{ name }}` w/ cluster generator can lead to DNS-1123 violations when using EKS

### ISSUE THREAD

**Issue by Lykathia** [argoproj-labs/applicationset#189]
Given an ApplicationSet with a declaration like

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{ name }}-demo'
  ....
```

Where an EKS cluster is being used, declared like
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: production-eks-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: arn:aws:eks:us-east-1:1234567890:cluster/eks-prod
  server: https://DCGUID1234567890.sk1.us-east-1.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-prod",
        "roleARN": "arn:aws:iam::1234567890:role/eks-prod-irsa-cross-account-access-argocd"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "..."
      }
    }
```

The following error emits from the applicationset controller:

> 2021-04-07T18:59:07.308Z ERROR controller-runtime.manager.controller.applicationset Reconciler error {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "demo", "namespace": "argocd", "error": "Application.argoproj.io \"arn:aws:eks:us-east-1:1234567890:cluster/eks-prod-demo\" is invalid: metadata.name: Invalid value: \"arn:aws:eks:us-east-1:1234567890:cluster/eks-prod-demo\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"}

This may just be a documentation thing I am missing. I am unsure how to now achieve uniqueness w/ application set while using a multi cluster EKS setup + cluster generator.

It looks like annotating a custom label might be the way to go here - however the default cluster can not be annotated, as it is not registered as a secret like the other clusters.

The only other workaround I am seeing is using a list generator and just manually updating when new clusters are added/removed.

Noted that in terms of a declarative setup, this failure is only seen in the logs -- and by omission of the additional cluster in the GUI. Everything seems OK with no errors at a glance otherwise.
![image](https://user-images.githubusercontent.com/1256508/113921326-3db74980-97bc-11eb-8f02-7e9a7011dbe8.png)
