### ISSUE TITLE
filter git directories generator based on files inside it

### ISSUE THREAD

**Issue by LiorLieberman** [argoproj-labs/applicationset#199]
Hi all, 

We are using applicationset to provision helm applications to all our environments.

We are templating each environment with value-<env>.yaml file

We have a use case now which we do not need all the applications generated from the applicationset in all environments.

For some environments we do not need to include all apps

I suggest adding an option to repo_service (feel free to advise somewhere else) to filter only applications with the requested value-file name.

That way we could have different applications on different environments generated with applicationset.

What do you think?

**Comment by jgwest** [comment]
Hi @LiorLieberman, would you be able to provide an example of what you mean?

**Comment by LiorLieberman** [comment]
Hi @jgwest sure.

Most of us have multiple environments, and the not every application is desired in every environment.
In our use case for example we provision helm applications using values-<env-name>.yaml file.
Therefore I thought it would be great if the generator, git generator for example will check if under the directories we have such values-<envname>.yaml file. and just if there is  the applicationset will provision new application.

A good example would be a cluster for Production and a cluster for Dev.
Lets take [this](https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook) directory from argo-cd-example apps repo. 
For simplicity lets say Applicationset is configured like that  (only provision one applications).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj/argocd-example-apps.git
      revision: HEAD
      directories:
      - path: helm-guestbook
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - value.yaml
            - values-production.yaml (it dev it would be values-dev.yaml)
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
```

So what i suggest is having another filter layer that telling Applicationset to check for this specific file in the directory and just if it has this file it will include create the application. In the example above we would have `helm-guestbook` app in production but not in Dev

What do you think?

**Comment by jgwest** [comment]
Sounds good, having the ability to target particular directories based on the presence of matching a path filter makes sense to me, and I agree this sounds like something that would be useful to enough folks to make it worth adding. Did you have an example in mind re: how to add this feature to the ApplicationSet Git generator spec?

**Comment by LiorLieberman** [comment]
Thinking maybe to add it into repo_service, GetDirectories function, but I am not sure this is the right place.
Regarding the key in the spec, I think we could have another optional key under `directories` like `pathExists` or  a `filters` struct and inside it `pathExists` or `directoryFileExists`.

example 1:
```yaml
directories:
- path: *
  pathExsits: a.yaml
```

example2:
```yaml
directories:
- path: *
  filters:
  - directoryFileExists: a.yaml
```

**Comment by jgwest** [comment]
Cool, how about this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj/argocd-example-apps.git
      revision: HEAD
      directories:
      - path: apps
        onlyIncludeWithFileMatch:
          # (an array of strings that match filepath.Match expressions)
          - values1.yaml  # You can just specify a file name
          - "*.yaml" # Or a wildcard string that matches filepath.Match syntax (https://golang.org/pkg/path/filepath/#Match)
```

*onlyIncludeWithFileMatch*: This is a bit longer than `pathExists` or `directoryFileExists`, but I think it's still acceptable, and has the advantage of concisely explaining the behaviour: only include the directory if a file matches.
- It contains an array of strings, which lets the user specify multiple values (which could be useful)
- Those string are filepath.Match expressions, which give a bit more flexibility than just a simple filename.

What do you think?
