### ISSUE TITLE
git generator for branch

### ISSUE THREAD

**Issue by fabricev** [argoproj-labs/applicationset#200]
Could be convenient to have a generator for branches (following a given pattern):

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-releases
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      branches:
      - name: 'test_*'
  template:
    metadata:
      name: 'myapp-{{branch}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: {{ branch }}
        path: 'app/manifests'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{branch}}'
```

Would manage the apps dynamically based on the various test_ branches of the repo.
