### ISSUE TITLE
Feature request: Be able to discover all Pull Requests in a GitHub repository

### ISSUE THREAD

**Issue by dhenneke** [argoproj-labs/applicationset#210]
We often do feature-branch/PR deployments to see if our application would work with the given change and use the argo-cli to dynamically create `Application`s from our build server. But it would be nice if an `ApplicationSet` could periodically discover all Pull Requests of a repository. This is similar to https://github.com/argoproj-labs/applicationset/issues/200 but based on the GitHub API and with the option to filter by label to be a bit more flexible on which PR should actually be deployed.

Something like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-releases
spec:
  generators:
  - githubPullRequests:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      labels:
      # only PRs that with the label 'preview'
      - name: 'preview'
  template:
    metadata:
      name: 'myapp-{{ pr-number }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: {{ pr-branch }}
        path: 'app/manifests'
        kustomize:
          nameSuffix: pr-{{ pr-number }}
          # depending on the setup, this would also allow overrides
          # of specific images for PRs from service repositories
          images:
          - my-image:{{ pr-head-sha }}
      destination:
        server: https://kubernetes.default.svc
        namespace: 'my-project-pr-{{ pr-number }}'
```
