### ISSUE TITLE
Kustomize install fails with kubectl

### ISSUE THREAD

**Issue by rdpa** [argoproj-labs/applicationset#22]
Install fails when using kustomize version 2.X that is bundled with kubectl.

Kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj-labs/applicationset/manifests/cluster-install/?ref=567ab7c
```

Command:
```bash
$ kubectl apply -k ./
error: AccumulateTarget: AccumulateTarget: rawResources failed to read Resources: Load from path ../namespace-install failed: '../namespace-install' must be a file (got d='/private/var/folders/pv/r1tbm8n92mx9t46kqx68bz6c0000gn/T/kustomize-667102827/manifests/namespace-install')
```

Changing `resources` to `bases` in namespace-install and cluster-install will fix this.
