### ISSUE TITLE
Application set not able to delete k8s resources of child application

### ISSUE THREAD

**Issue by mksha** [argoproj-labs/applicationset#230]
Hi,
I, currently have a application set (parent), which creates a child argo application (child).
When i delete the argo parent app or application set it does not remove the child application k8s resources at all and leave them behind.

Argo cd details:

argocd: v2.0.1+33eaf11.dirty
  BuildDate: 2021-04-21T18:44:13Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: dirty
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0

**Comment by mksha** [comment]
@jgwest @rtnpro pls have a look at above issue

**Comment by jgwest** [comment]
Hi @mksha, what version of ApplicationSet controller?

**Comment by rtnpro** [comment]
I see here: https://github.com/argoproj-labs/applicationset/blob/master/pkg/controllers/applicationset_controller.go#L549 that ApplicationSet controller uses the Kubernetes Controller client to delete the `Application` specs it created.

@mksha Do you mean that the `Application` specs generated by `ApplicationSet` do not get removed when `ApplicationSet` is deleted? Or the k8s resources like `deployment`, `service`, etc. created by the ArgoCD `Application` do not get deleted?

**Comment by mksha** [comment]
Application Controller version :  https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.1.0/manifests/install.yaml
@jgwest

**Comment by mksha** [comment]
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  # A cascade delete, deletes both the app and its resources, rather than only the app.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: ssh://git@git.something.com:8728/test/myapp.git
      revision: feature/application-set-svc
      files:
      - path: "apps/**/config.json"
  template:
    metadata:
      name: '{{app.instance}}-interest'
    spec:
      project: my-project
      source:
        repoURL: 'https://artifactory.xxx..com/artifactory/helm/'
        chart: java-webapp
        targetRevision: 0.0.4
        path: .
        # helm specific config
        helm:
          # Values file as block file
          values: '{{values}}'
      destination:
        namespace: my-namespace
        name: '{{cluster.name}}'
      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: true # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - Validate=true # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
        - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
        - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
        - ApplyOutOfSyncOnly=true # to skip syncing resources that are already in the desired state.
        - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
        # The retry feature is available since v1.7
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

**Comment by mksha** [comment]
then in my repo i have apps/dev/config.json
@jgwest  @rtnpro

**Comment by mksha** [comment]
when i delete the dev folder from repo then application set deletes the app created for dev, but does not delete the k8s resources of that app.

**Comment by jgwest** [comment]
You should not add this finalizer to the ApplicationSet:
```
  finalizers:
    - resources-finalizer.argocd.argoproj.io
``

This finalizer is only supported on Argo CD `Application` objects. It's likely this finalizer is preventing the ApplicationSet from being deleted.

**Comment by mksha** [comment]
is there any logs that i can see that is tries to delete the k8s resources .
in which deployment should i take a look in argo for debugging this issue

**Comment by mksha** [comment]
> You should not add this finalizer to the ApplicationSet:
> 
> ```
>   finalizers:
>     - resources-finalizer.argocd.argoproj.io
> ```
> 
> This finalizer is only supported on Argo CD `Application` objects. It's likely this finalizer is preventing the ApplicationSet from being deleted, which is what is causing your issue.

I also tried without that, but does not work

**Comment by mksha** [comment]
again, i am not deleting the application itself, i am delete one of the application created by application set.

**Comment by jgwest** [comment]
You should not delete an individual application that is managed by an ApplicationSet; if you do, the ApplicationSet controller will immediately recreate it, eg I don't think deleting an individual Application will accomplish what you are looking for.

In any case, the actual deletion of an Application's child resources is handled by Argo CD, rather than the ApplicationSet controller.

**Comment by mksha** [comment]
again, i am not doing manually, as my application set is monitoring a repo where i have multiple app
apps
-- app1
---app2
---app3

so applciation set will create a argo app for each folder.
and if i add 4th folder and commit mhy code argo will automatically create the new argo app 4 using application set.
but when i delete the folder , then application set automatically deletes the argo app, but not the k8s resources.
@jgwest @rtnpro

**Comment by jgwest** [comment]
Hi @mksha, I am not able to reproduce:

I create this example ApplicationSet, based on the one you specified:
```yaml

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jgwest/applicationset.git
      revision: test
      files:
      - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-interest'
    spec:
      project: default
      source:
        repoURL: https://github.com/jgwest/applicationset.git
        targetRevision: test
        path: "examples/git-generator-files-discovery/apps/guestbook"
      destination:
        namespace: '{{cluster.name}}'
        server: https://kubernetes.default.svc        
      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: true # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - Validate=true # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
        - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
        - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
        - ApplyOutOfSyncOnly=true # to skip syncing resources that are already in the desired state.
        - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
        # The retry feature is available since v1.7
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
```

I apply it, and see the ApplicationSet and Applications created.

I delete a `config.json` file from the `test` branch of https://github.com/jgwest/applicationset.git, which is what it is pointing to.

When the ApplicationSet generator reconciles the ApplicationSet, the Application is deleted, and so are the deployment resources that it created.
