### ISSUE TITLE
Matrix generator support for combining generator parameters with matching keys

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#236]
This issue and discussion was kicked off from the [excellent comment](https://github.com/argoproj-labs/applicationset/pull/205#issuecomment-840596910) from @winmillwill on the Matrix generator PR.

At present, if the Matrix generator's child generators produce parameters with matching keys, an error will be returned (unless the parameter keys exactly match). For example, @winmillwill noted that both the scmProvider and List generators will try to set a url parameter (ie a parameter named `url`).

We should definitely allow users to use the Matrix generator with generators that might produce matching parameters, and still allow them to refer to all possible parameters generates by both generators.

My initial thought was something like a `paramPrefix` field, which would add a user-defined prefix to every key that was generated by that generator:

```yaml
matrix:
  generators:
    - git:
        repoURL: 'https://github.com/argoproj-labs/applicationset.git'
        revision: HEAD
        directories:
          - path: examples/matrix/cluster-addons/*
      paramPrefix: git. # <--------------------------- This is a new field
    - list:
        elements:
          - cluster: engineering-dev
            url: 'https://1.2.3.4'
            values:
              project: dev
          - cluster: engineering-prod
            url: 'https://2.4.6.8'
            values:
              project: prod
      paramPrefix: list. # <--- New field
```
So if the list generator above generated (key -> value):
- cluster -> "cluster1"
- url -> "https://kubernetes.default.svc"

The paramPrefix of `list.` would modify these generated parameters to:
- list.cluster -> "cluster1"
- list.url -> "https://kubernetes.default.svc"

You can see `list.` is prepended to the key, with `list.` being the user provided value to prepend. This ensures that (presuming the user provides differing paramPrefixes for each generator) that there can be no overlap, and they can then refer to these parameters independently in the template.

So taken to it's logical conclusion, if the git generator generated:
- path -> (some path)
- path.basename -> (some basename)

It would be modified by the `git.` paramPrefix:
- git.path -> (some path)
- git.path.basename -> (some basename)

And the Application would be templated with these combined (by the matrix generator) sets of values:
- git.path -> (some path)
- git.path.basename -> (some basename)
- list.cluster -> "cluster1"
- list.url -> "https://kubernetes.default.svc"

(This isn't a perfect example, but hopefully it makes sense :sweat_smile:)

And it might look like this in the template:
```yaml
template:
    metadata:
      name: '{{git.path.basename}}'
    spec:
      project: some-project
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: HEAD
        path: some-path
      destination:
        server: '{{list.url}}'
        namespace: '{{git.path.basename}}'
```

Does this make sense? Any obvious flaws with the design, or any scenarios this wouldn't be able to handle? Any tricky implementation details? A better name for `paramPrefix`? A better alternative idea for how to handle this whole scenario? Feedback welcome!
