### ISSUE TITLE
Support log-level for controller logs

### ISSUE THREAD

**Issue by dorroddorrod** [argoproj-labs/applicationset#238]
**@jgwest EDIT:**
Enhancement Request: 
Add support for configurable log levels via [parameter](https://github.com/argoproj-labs/applicationset/blob/48a7b47da0552b9e5a518704e25489ab4a36645c/main.go#L81), eg the ability to set additional log levels beyond just the `--debug` parameter support we have now. For example, as requested, ability to set the log level to only show error or warn.

**Original Text from @dorroddorrod**
Hi,
Is there any way to control the log level for the application-set controller ?

**Comment by jgwest** [comment]
Hi @dorroddorrod , you can add `--debug` parameter to the `argocd-applicationset-controller` Deployment, eg:
`kubectl edit deployment/argocd-applicationset-controller`, and add this line:
```yaml
spec:
  template:
    spec:
      containers:
      - command:
        - applicationset-controller
        - --debug  # <-------- add this
```

Or you can edit the install.yaml, add the line as above, and reapply using `kubectl apply -f install.yaml`:
https://github.com/argoproj-labs/applicationset/blob/48a7b47da0552b9e5a518704e25489ab4a36645c/manifests/install.yaml#L3655
