### ISSUE TITLE
Failed to parse matrix generator

### ISSUE THREAD

**Issue by mksha** [argoproj-labs/applicationset#252]
While using matrix generator , getting validation error.

error validating data: ValidationError(ApplicationSet.spec.generators[0]): unknown field "matrix" in io.argoproj.v1alpha1.ApplicationSet.spec.generators

used spec

```
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: <git-repo-url>
          revision: feature
          files:
          - path: dev/apps/**/config.yaml
      - list:
          elements:
          - cluster: my-cluster
            url: mu-cluster-url
```
