### ISSUE TITLE
Option to exclude clusters based on label values

### ISSUE THREAD

**Issue by LS80** [argoproj-labs/applicationset#266]
An option to exclude certain clusters based on a label value would be useful. Something like adding `excludeLabels` alongside the existing `matchLabels` perhaps.

```yaml
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters:
      selector:
        excludeLabels:
          staging: true
```
