### ISSUE TITLE
ApplicationSet with git directories generator not recognizing `exclude`

### ISSUE THREAD

**Issue by pratikzingade** [argoproj-labs/applicationset#269]
I am using ArgoCD `v1.7.6+b04c25e` and I am just trying the POC for `ApplicationSet`. 

Installed ApplicationSet by running `kubectl`
```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.1.0/manifests/install.yaml
```

Here is my ApplicationSet file - 

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-application-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: <GIT REPO URL>
      revision: HEAD
      directories:
      - path: apps/overlays/dev/*
      - path: apps/overlays/dev/common
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: <GIT REPO URL>
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
```

When I check in ^^ file or just type `kubectl apply -f dev-app-discovery.yaml -n argocd` I see that it does not recognize `exclude` path. 
I want `apps/overlays/dev/common` to be excluded and I don't want an application to be created for `common` folder.

Getting the following error - 
```
$ kubectl apply -f dev-app-discovery.yml -n argocd
error: error validating "dev-app-discovery.yml": error validating data: ValidationError(ApplicationSet.spec.generators[0].git.directories[1]): unknown field "exclude" in io.argoproj.v1alpha1.ApplicationSet.spec.generators.git.directories; if you choose to ignore these errors, turn validation off with --validate=false
```

Thanks,
Pratik
