### ISSUE TITLE
Can't see applicationset into ArgoCD ui

### ISSUE THREAD

**Issue by gerardgorrion** [argoproj-labs/applicationset#276]
Hi all,

We are deploying argocd with some applicationset. current config of application set:

Installation argocd:
```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.1.0/manifests/install-with-argo-cd.yaml
```

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: pro
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-services'
    spec:
      project: default
      source:
        repoURL: <bitbucket private url>
        targetRevision: HEAD
        path: '{{cluster}}/service'
      destination:
        server: '{{url}}'
        namespace: default
```

The applications of the repo was deployed into cluster destination, but only see the application deployed, not the applicationset, like this screenshoot:

#218

How can we do to manage applicationsets into argocd ui?

Regards,
