### ISSUE TITLE
Git directories generator does not iterate over particular sub-directory inside folders 

### ISSUE THREAD

**Issue by hanzala1234** [argoproj-labs/applicationset#285]
I have my gitops directory structure as follows

```
01-app
   |-  01-dev
        |-  deployment.yaml
        |-  service.yaml
   |- 02-stage 
        |- deployment.yaml
        |- service.yaml
02-app
   |-  01-dev
        |-  deployment.yaml
        |-  service.yaml
   |- 02-stage 
        |- deployment.yaml
        |- service.yaml 
```

I want to write _ApplicationSet_ that will pick 01-dev folder inside all application folder and create "Application" for that. I tried below code but it did not generate any "Application"

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: <repo>
      revision: <revision>
      directories:
      - path: "**/01-dev/"
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: openshift-stakater-argocd
    spec:
      project: default
      source:
        repoURL: <repo>
        targetRevision: option-2
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
```

Am I writing a wrong regex or its not supported at all? 

I have different clusters and argocd deployment for different environment. I want to write applicationset that will deploy all applications **dev** environment

**Comment by jgwest** [comment]
@hanzala1234 Try removing the `/` from the end, eg:
```yaml

  generators:
  - git:
      repoURL: <repo>
      revision: <revision>
      directories:
      - path: "**/01-dev"  # <----
# (...)
```
This worked for me. If this works for you, let me know and I'll update the docs to better communicate this.
