### ISSUE TITLE
"Could not read Username for 'https://gitlab.com'" when using private Gitlab repositories with the git generator

### ISSUE THREAD

**Issue by zwennesm** [argoproj-labs/applicationset#286]
Hello there,
I am seeing some strange errors regarding authentication when trying to generate applications based on a git directory located on a private Gitlab repository. Could it be that the applicationsets controller is currently not using the secrets from the argocd namespace with a `argocd.argoproj.io/secret-type: repository` tag?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://gitlab.com/GROUP/PROJECT.git
        revision: argocd
        directories:
          - path: cluster-addons/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: core
      source:
        repoURL: https://gitlab.com/GROUP/PROJECT.git
        targetRevision: argocd
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
```

Logs returned by the applicationset controller:

```
│ time="2021-07-06T13:02:29Z" level=info msg="git fetch origin --tags --force" dir="/tmp/https:__gitlab.com_GROUP_PROJECT" execID=jqRY4                                                                                              │
│ time="2021-07-06T13:02:29Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.com': No such device or address" execID=jqRY4                                  │
│ time="2021-07-06T13:02:29Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir="/tmp/https:__gitlab.com_GROUP_PROJECT" operation_name="exec git" time_ms=327.565585                                                 │
│ time="2021-07-06T13:02:29Z" level=error msg="error generating params" error="Error during fetching repo: `git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.com': No such devi │
│ time="2021-07-06T13:02:29Z" level=error msg="error generating application from params" error="Error during fetching repo: `git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.c │
│ 2021-07-06T13:02:29.614Z    ERROR    controller-runtime.manager.controller.applicationset    Reconciler error    {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "core", "namespace": "argocd", "error" │
│ github.com/go-logr/zapr.(*zapLogger).Error
```

**Comment by jgwest** [comment]
Hi @zwennesm , it looks like this is an issue with an earlier release of Argo CD:
https://github.com/argoproj/argo-cd/issues/6228

To get around it, you can first install latest Argo CD:
https://argoproj.github.io/argo-cd/getting_started/#1-install-argo-cd
This will install Argo CD v2.0.4, which is newer than the one packaged with ApplicationSet controller, and should contain the fix.

Then, install ApplicationSet controller using the 'install into an existing Argo CD install' instructions:
https://argocd-applicationset.readthedocs.io/en/stable/Geting-Started/#install-applicationset-into-an-existing-argo-cd-install

**Comment by zwennesm** [comment]
Hey there @jgwest, thanks for looking into this.

I was already running the `latest` version so I am not sure if that's the problem. I tested the same `ApplicationSet` with versions: `v2.0.4`, `master`, and `release-2.0-hotfix`, but the same problem occurs with all versions.

Just for full information, my secret looks like this:

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repository
  namespace: argocd
data:
  password: PERSONAL_ACCESS_TOKEN
  url: https://gitlab.com/GROUP/PROJECT.git
  username: USERNAME
```
