### ISSUE TITLE
Support for extracting parent path/base names for Git file/directory generators {{path}}

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#293]
As discussed [here](https://cloud-native.slack.com/archives/C01U45M2SVB/p1626115983314500) (amongst other places), there exists an obvious need with the Git generator to extract components of paths for use in ApplicationSet templates.

At present (on the [master](https://argocd-applicationset.readthedocs.io/en/master/Generators-Git/) branch), the Git file and Git directory generators generate the following parameters:
- `{{path}}`: path of discovered (directory/config file) within the repository, e.g. `/path/to/apps/app1` or `/path/to/config/config.json`
- `{{path.basename}}`: name of discovered (directory/config file) within the repository, eg `app1` or `config.json`

It would be beneficial to extend this to allow templates to use parent folder names/paths as well, we just need to discuss the format and behaviour for this.

### What format should this take?
- `{{path[1]}}`: Return the path to the parent file/folder of the discovered (directory/config file), for example `/path/to/apps` or `/path/to/config`
- `{{path[1].basename}}`: Return the path to the name of the parent file/folder of discovered (directory/config file), for `apps` or
- `{{path[0]}}`: Would have the same value as `{{path}}` (likewise for basename)
- Another format? Any other prior art we can draw upon here? (Does Helm support something like this? What format does it use?)
    - `{{path~1}}`/`{{path~1.basename}}`?
    - `{{path[len-1]}}`/{{path[len-1].basename}}`?

### What should the behaviour be if a path doesn't exist (eg `{{path[4]}}` for a path only containing 2 components)
- throw error and return (my personal preference, but does this break any useful patterns?)
- silently ignore
- empty string

**Comment by benjamin-bergia** [comment]
Hi @jgwest,

I happen to be testing applicationset and I am stuck to this exact same issue. My apps are using the following directory layout `./applicationName/environments/namespaceName`. Currently, there is no way for me to retrieve the `applicationName`. Could you give few more examples? I initially thought that `{{ path }}` could be a simple list of the files that has been found with their path split by `/`.
For example, in my case, `path` would contain `['applicationName', 'environments', 'namespaceName']`. Then I could get my `applicationName` by using `{{ path[0] }}`. If I wanted the whole path as a single string it would require a method like `{{ path.toString() }}` or `{{ path.join('/') }}`. In case the item doesn't exist it should throw an error but it would be nice to offer a `{{ path[4].withDefault('test') }}`.

I am not sure if this correspond to the example you gave.

**Comment by elocke** [comment]
Leaving a note here that I'm in the same situation and hacked some stuff together with file generators that are just:

```
  name: 
  namespace
```

would make my directories cleaner if I could do path[0]. although I think I would like to be able to do reverse ordering in case of a folder being nested deeper

**Comment by RumRogerz** [comment]
> Same situation for me with Git Generator.
> I've got this directory structure:
> `level1/CLUSTER-NAME/level2/level3/*`
> 
> I seriously thought a Jinja2 parser was implemented in this so I could simply do something like:
> 
> `spec.template.metadata.name: {{ path[1] }}-{{ path.basename }}`
> 
> or alternatively:
> 
> `spec.template.metadata.name: {{ path | split("/")[1] }}-{{ path.basename }}`
> 
> but nonetheless this doesn't work. Looking forward for this enhancement to be implemented.

Came here to say this. My ApplicationSets will be hella cleaner and my bosses will think I'm some sort of templating demi god.

**Comment by bradmccoydev** [comment]
Hey, @jgwest I would like to pick this issue up, can you please assign it to me?

**Comment by svmaris** [comment]
How about adding regex support to the git generator?

Something like this:

```yaml
spec:
  generators:
    - git:
        repoURL: ssh://git@xxxx
        revision: HEAD
        directories:
          - pathRegexp: deployments/(?P<namespace>(argo|other-namespace|another))/(?P<appname>.*)
  template:
    metadata:
      name: '{{pathRegexp.appname}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{pathRegexp.namespace}}'
```

**Comment by jwalitptl** [comment]
is this feature will be available in the next release?

**Comment by bogatuadrian** [comment]
I have a couple of suggestions for @jgwest's questions.

### What format should this take?

#### 1. User-controlled components

Instead of allowing arbitrary access to any path component, we could allow the user to specify the components of interest from the generator (instead of from the template). An example based on the initial Slack [discussion](https://cloud-native.slack.com/archives/C01U45M2SVB/p1626115983314500) linked:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  generators:
    - git:
        repoURL: git@bitbucket.org:my-org/my-repo.git
        directories:
          - path: apps/*/deployment/overlays/*
            # object defining template parameters of the form `path.components.<key>`
            # that expose the path component matched by `path`, at the corresponding index
            components:
              root: 0 # this would point to the first path component, i.e. "apps"
              app: 1 # this would point to the 2nd path component (first glob)
              env: 4 # this would point to the 5th path component (second glob)

          # when having multiple dirs with different structures, this solution is useful
          # because path components can be shifted and `{{ path[1] }} would point
          # to different things for different entries in `directories`
          - path: addons/apps/*/deployment/overlays/*
            components:
              app: 2 # this keeps the `{{ path.components.app }}` correct & consistent

  template:
    metadata:
      name: 'app-{{ path.components.app }}-deployment-{{ path.components.env }}'
    spec:
      # ...
```

Advantages:
* perhaps easier to implement
* works well with multiple directories that have different structures

For me, this would be the preferred solution.

#### 2. Composable Unix-like syntax

Another way to do this would be to use something resembling composable `basename`/`dirname` operations, and allow template parameters like `{{ path.dirname.dirname.dirname.basename }}`.

After a quick glance at the code, this might be a bit harder to implement with the current templating engine as you would need to provide all the possible combinations of `.dirname` and `.basename`.
