### ISSUE TITLE
Ability to have default templated values or sprig usage in template

### ISSUE THREAD

**Issue by vavdoshka** [argoproj-labs/applicationset#303]
It would be useful to have a way to set the default values in the template where dynamic values are being used. As an example with git generator: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: some-application-set
spec:
  generators:
  - git:
      repoURL: some@repo.git
      revision: HEAD
      files:
      - path: "_argocd/apps/*.json"
  template:
    metadata:
      name: {{target-cluster.namespace}}.{{target-cluster.name}}
    spec:
      project: some-project
      source:
        repoURL: some@repo.git
        targetRevision: {{source-directory.revision}}
        path: {{source-directory.path}}
        plugin:
          name: helmfile
      destination:
        name: {{target-cluster.name}}
        namespace: {{target-cluster.namespace}}
      syncPolicy:
        automated: 
          prune: {{target-cluster.syncAutomated}}
```

And Let’s say we have these generator data:
1.
```yaml
{
  "target-cluster": {
    "name": "production",
    "namespace": "mynamespace",
    "syncAutomated": false
  },
  "source-directory": {
    "path": "myapp",
    "revision": "production"
  }
}
```

2.
```yaml
{
  "target-cluster": {
    "name": "staging",
    "namespace": "mynamespace",
    "syncAutomated": true
  },
  "source-directory": {
    "path": "myapp",
    "revision": "master"
  }
}
```

And this will work, but if one has to create many applications all across different clusters/environments/namespaces it will look redundant to specify the same values for majority of the applications. So one would want to minimize the scope of the data, by providing only what is relevant, for example, one can have some proper defaults for `target-cluster.syncAutomated = false` and `source-directory.revision = master`.

So the generator data might become something like:
```yaml
1.
{
  "target-cluster": {
    "name": "production",
    "namespace": "mynamespace",
  },
  "source-directory": {
    "path": "myapp",
    "revision": "production"
  }
}
```
2.
```yaml
{
  "target-cluster": {
    "name": "staging",
    "namespace": "mynamespace",
    "syncAutomated": true
  },
  "source-directory": {
    "path": "myapp",
  }
}
```

Needless to say that the ability of `sprig` usage would cover this and some other useful use-cases.
