### ISSUE TITLE
Git generator with a git repository using a custom CA fails

### ISSUE THREAD

**Issue by bo0ts** [argoproj-labs/applicationset#305]
I'm trying to use git generator with a git repository that uses a custom CA. 

The certificate is configured in argocd itself and I can use the repository there without a problem or without specifying insecure connections.

Is this a bug in applicationset? Is there a way to provide a certificate or allow insecure connections?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foobar-as
spec:
  generators:
  - git:
      repoURL: https://gitlab.intern/myrepo.git
      revision: master
      directories:
      - path: foobar/*
  template:
    metadata:
      name: 'foobar-{{path.basename}}'
    spec:
      project: foobar
      source:
        repoURL: https://gitlab.intern/myrepo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: foobar
        namespace: default
```

This is the error in the application set controller:

```
time="2021-07-22T12:46:06Z" level=info msg="git fetch origin --tags --force" dir="/tmp/https:__gitlab.intern_myrepo" execID=oN3gL
time="2021-07-22T12:46:06Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: fatal: unable to access 'https://gitlab.intern/myrepo.git/': server certificate verification failed. CAfile: none CRLfile: none" execID=oN3gL
time="2021-07-22T12:46:06Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir="/tmp/https:__gitlab.intern_myrepo" operation_name="exec git" time_ms=70.99395799999999
time="2021-07-22T12:46:06Z" level=error msg="error generating params" error="Error during fetching repo: `git fetch origin --tags --force` failed exit status 128: fatal: unable to access 'https://gitlab.intern/myrepo.git/': server certificate verification failed. CAfile: none CRLfile: none" generator="&{0xc0003985a0}"
2021-07-22T12:46:06.605Z	ERROR	controller-runtime.manager.controller.applicationset	Reconciler error	{"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "central2-as", "namespace": "argocd-clustermgmt", "error": "Error during fetching repo: `git fetch origin --tags --force` failed exit status 128: fatal: unable to access 'https://gitlab.intern/myrepo.git/': server certificate verification failed. CAfile: none CRLfile: none", "errorVerbose": "`git fetch origin --tags --force` failed exit status 128: fatal: unable to access 'https://gitlab.intern/myrepo.git/': server certificate verification failed. CAfile: none CRLfile: none\nError during fetching repo\ngithub.com/argoproj-labs/applicationset/pkg/services.checkoutRepo\n\t/workspace/pkg/services/repo_service.go:159\ngithub.com/argoproj-labs/applicationset/pkg/services.(*argoCDService).GetDirectories\n\t/workspace/pkg/services/repo_service.go:84\ngithub.com/argoproj-labs/applicationset/pkg/generators.(*GitGenerator).generateParamsForGitDirectories\n\t/workspace/pkg/generators/git.go:78\ngithub.com/argoproj-labs/applicationset/pkg/generators.(*GitGenerator).GenerateParams\n\t/workspace/pkg/generators/git.go:62\ngithub.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).generateApplications\n\t/workspace/pkg/controllers/applicationset_controller.go:349\ngithub.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).Reconcile\n\t/workspace/pkg/controllers/applicationset_controller.go:93\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
github.com/go-logr/zapr.(*zapLogger).Error
```

**Comment by jgwest** [comment]
HI @bo0ts, interesting, this should be working (eg your scenario as described is supported), are you by chance installing Argo CD via either the Argo CD operator (or the OpenShift GitOps operator which is based on it), or the ApplicationSet helm chart? Eg rather than using the `install.yaml` from the ApplicationSet install? (I ask because there was an issue with [`volumes`](https://github.com/argoproj-labs/applicationset/blob/c7b34ea9572c1e7549c1564da6367a27aecc7efc/manifests/base/deployment.yaml#L39) fields not being correctly populated in some of those, at various points...)

**Comment by bo0ts** [comment]
@jgwest Thanks for the quick reply. ApplicationSet controller is installed via ArgoCD operator 0.0.15 (installed via OLM in OKD 4.5). The abridged ArgoCD CR is:

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    app: argocd
spec:
  applicationSet: {}
```
