### ISSUE TITLE
Applicationset controller pod crash when git files generator detects wrong value in a json file

### ISSUE THREAD

**Issue by rotemjac** [argoproj-labs/applicationset#311]
Below is my setup.

1) The 'git-generator-files.yaml':

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/some-user/app-of-apps
        revision: HEAD
        files:
          - path: "my-deployment/cluster-config/**/*.json"
  template:
    metadata:
      name: '{{tenant.name}}'
    spec:
      project: my-deployment
      source:
        repoURL: http://some-test.s3-website-us-east-1.amazonaws.com/databases
        chart: argo-with-crossplace
        targetRevision: 1.1.0
        helm:
          parameters:
            - name: servers_count
              value: '{{tenant.servers_count}}'
            - name: schedulers
              value: '{{tenant.schedulers_count}}'
            - name:workers
              value: '{{tenant.workers_count}}'
```

2) The relevant part in one of the json files under 'my-deployment/cluster-config/some-folder/some-file.json':

```
{
  "tenant": {
    "name": "my-tenant",
    
     "servers_count": 1,
     "schedulers_count": 1,
     "workers_count": 1
     
    },
    "source": {
      "chart": {
        "version": "1.0.1"
      }
    }
  }
}
```

Inserting the integer value of 1 instead of string value of "1" in all the "*_count" fields above will cause the Applicationset controller pod to crash with the following error:

`E0725 18:28:21.249579 1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1c39b00), concrete:(*runtime._type)(0x1bb2d00), asserted:(*runtime._type)(0x1bf2080), missingMethod:""} (interface conversion: interface {} is float64, not string)`

Expected result:
Receiving an error or a warning without the pod crashing.
