### ISSUE TITLE
ApplicationSet spec.destination.server does not support named servers in 0.1.0

### ISSUE THREAD

**Issue by bo0ts** [argoproj-labs/applicationset#315]
ArgoCD Applications allow for `destination.server` to be the name of a cluster instead of the adress. The validation of applicationset does not seem to take this into account and does not create the applications.

```
apiVersion: v1
kind: Secret
metadata:
  name: foo-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: foo
  server: https://foo:6443
  config: ...
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  finalizers:
    - manual-deletion
spec:
  generators:
  - git:
      repoURL: ....
      revision: master
      directories:
      - path: ./*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: ...
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: foo
        namespace: {{path.basename}}
```

Results in error:

```
time="2021-07-27T09:39:21Z" level=error msg="application spec is invalid: InvalidSpecError: cluster 'foo' has not been configured"
```

**Comment by jgwest** [comment]
Hi @bo0ts, in your example I believe this should be:
```yaml
      destination:
        # server: foo  - this is the url field
        name: foo # this is the name field
        namespace: {{path.basename}}
```

The `server` field is used for the URL, and the `name` refers to the name of the cluster. Let me know if this doesn't solve the issue... (it's perhaps not the clearest terminology, but we inherit this from Argo CD spec)
