### ISSUE TITLE
[Feature] Cluster name generator

### ISSUE THREAD

**Issue by gebn** [argoproj-labs/applicationset#316]
Firstly, thanks for creating the `ApplicationSet` resource - it saves a lot of duplication. This is a feature request/design doc for a new selection mechanism on the cluster generator that simply takes a list of cluster names, and generates `Application`s as if that set had been selected via labels.

### Motivation

Developers are familiar with cluster names, but aren’t necessarily aware of API server URLs. To use the list generator, they have to find this information, and may copy the wrong URL. Given all clusters have to already be specified in Argo CD, we can look up the URL from the name, halving the size of the list config and reducing the opportunity for error, while providing additional metadata for each cluster (labels and annotations). This is a kind of hybrid between the list and cluster generator, providing the same parameter values as the latter, while allowing users to specify a set of clusters that may not be selectable via any single label set.

### Configuration

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters:
      names:  # new key, alternative to "selector"
      - cluster1
      - cluster2
      values:
        foo: bar
  ...
```

The new `names` key is logically an alternative to the existing `selector` key. Both could be used at the same time and the union taken, however I can't think of a use case for this, so would prefer to be stricter for the time being (this can be easily changed without creating a conflict). For each list item, the controller would retrieve the secret for the cluster with the supplied name, and make the `name`, `server`, `metadata.labels.*` and `metadata.annotations.*` available in the template, in exactly the same way as when selecting via labels. The existing `values` key can be specified to attach additional parameters to every generated cluster.

What do you think? If this sounds reasonable, I'm happy to begin a PR.

**Comment by r0bj** [comment]
@gebn assuming that clusters are defined in Argo CD with names we could do something like this:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
      - cluster: cluster1
  template:
    metadata:
      name: 'myapp-{{cluster}}'
    spec:
      project: default
      source:
        path: apps/myapp
        repoURL: git@github.com:myorg/apps.git
        targetRevision: HEAD
      destination:
        name: '{{cluster}}'
        namespace: prod
```
Does it cover your use case?

**Comment by gebn** [comment]
@r0bj The more-flexible list generator in v0.2 gets us a lot closer. We'd still be missing the `metadata.labels.*` and `metadata.annotations.*` attributes pulled from cluster secrets. I think this PR still reduces the likelihood of error, however at a push they could all be reproduced in the config. It's certainly less of an improvement than for v0.1, which shows this project is moving in the right direction!

**Comment by r0bj** [comment]
Another option would be to label existing cluster secrets with `name=<cluster_name>' and then:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          name: cluster1
  - clusters:
      selector:
        matchLabels:
          name: cluster2
  template:
    metadata:
      name: 'myapp-{{name}}'
    spec:
      project: default
      source:
        path: apps/myapp
        repoURL: git@github.com:myorg/apps.git
        targetRevision: HEAD
      destination:
        name: '{{name}}'
        namespace: prod
```

**Comment by gebn** [comment]
@r0bj I prefer this, however I don't think it allows selecting the local cluster without selecting all others.

**Comment by voldemortensen** [comment]
@gebn you should be able to get only the local cluster with something like this (untested):

```yaml
selector:
  matchExpressions:
    - {key: argocd.argoproj.io/secret-type, operator: DoesNotExist}
```
