### ISSUE TITLE
Allow Git Files Generator to refer to one file per application

### ISSUE THREAD

**Issue by gulativishwas** [argoproj-labs/applicationset#323]
### Motivation
Currently, the Git file Generator supports creation of applications for multiple environments by creating 
config.json/yaml files for each environment. The number of config files increases rapidly if the number of environments
is large.
We tried using the Matrix Generator (Git File Generator and Cluster Generator) with a directory structure as follows:
```yaml
# cluster-deployments
# ├── apps
# │   ├── app1
# │   │   ├── appset.yaml
# │   │   ├── dev
# │   │   │   └── config.yaml
# │   │   ├── staging
# │   │   │   └── config.yaml
# │   │   ├── prod_client_1
# │   │   │   └── config.yaml
# │   │   ├── prod_client_2
# │   │   │   └── config.yaml
# │   │   └── prod_client_n
# │   │       └── config.yaml
# │   ├── app2
# │   │   ├── appset.yaml
# │   │   ├── dev
# │   │   │   └── config.yaml
# │   │   ├── staging
# │   │   │   └── config.yaml
# │   │   ├── prod_client_1
# │   │   │   └── config.yaml
# │   │   ├── prod_client_2
# │   │   │   └── config.yaml
# │   │   └── prod_client_n
# │   │       └── config.yaml
``` 
The appset and config file that we have created:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-appset
spec:
  generators:
  - matrix:
      generators:
        - git:
              repoURL: ...
              revision: HEAD
              files:
              - path: "apps/app1/**/config.yaml"
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{app.name}}-{{metadata.labels.app.kubernetes.io/environment}}'
    spec:
      project: default
      source:
        repoURL: '{{app.url}}'
        targetRevision: '{{app.version}}'
        path: '{{app.path}}'
      destination:
        server: '{{server}}'
        namespace: '{{app.namespace}}'
```
/apps/app1/dev/config.yaml
```yaml
app:
  name: app1
  namespace: the-namespace
  url: the-url
  version: HEAD
```
/apps/app1/prod_client_1/config.yaml
```yaml
app:
  name: app1
  namespace: the-namespace
  url: the-url
  version: 0.1.1
```

### Challenges
1. As it is evident from the sample config.yaml files, the only thing that varies is the `version` of the application.
Since, we are going to have nearly 200 environments, we would have to create & manage a lot of config files just to have
varying versions for the environments.
1. Also, the matrix generator creates applications for all the directories & target clusters (similar to a cartesian product).

### Proposal
We want to propose a new generator (or possibly an extension of the Git File Generator) which would read a single config
file per application that has all the environment versions defined in one place and create an ArgoCD application for it.
A sample config.yaml could look like this:

/apps/app1/config.yaml
```yaml
app:
  name: app1
  namespace: the-namespace
  url: the-url
  versions:
    dev: HEAD
    staging: 0.1.3
    prod_client_1: 0.1.1
    prod_client_2: 0.1.2
```

The directory structure would be reduced to:

```yaml
# cluster-deployments
# ├── apps
# │   ├── app1
# │   │   ├── appset.yaml
# │   │   └── config.yaml
# │   ├── app2
# │   │   ├── appset.yaml
# │   │   └── config.yaml
```

### Open Question(s)

1. For ensuring the intended number of applications are generated, can we use either [Cluster Decision Resources](https://github.com/argoproj-labs/applicationset/blob/master/examples/clusterDecisionResource/ducktype-example.yaml)
or [filters](https://github.com/argoproj-labs/applicationset/blob/master/examples/design-doc/proposal/filters.yaml) in the appset?

**Comment by jgwest** [comment]
Thanks for the detailed explanation of how you are using the existing generators, and for your use case! This is very helpful for helping myself and others as we reason about how folks are using ApplicationSets to model and deploy their application repository file/folder structures. It's definitely the case that the Git file generator has a tendency to devolve into the need to manage a bunch of small, mostly duplicated files, which is less than ideal.

Re: your proposed sample configuration file, I'm curious:
- Would it support arbitrary config.(json/yaml) files, or  do they need to conform to a format very close to your example?
- What would be your suggested algorithm for converting the structure of an appropriately formatted JSON/YAML file into parameters to substitute into `template` field Application?

**Comment by gulativishwas** [comment]
Thanks for reviewing this!

Adding my thoughts on your questions:

> Would it support arbitrary config.(json/yaml) files, or do they need to conform to a format very close to your example?

I feel that all the fields in config.json/yaml could be arbitrary.
The requirement is for the Generator to generate applications for all the enviroments if the versions are listed, if they are not,
it should simply function like the current Git Files Generator.

Somewhat like:
```yaml
field-1: value-1
field-2: value-2
versions: # this field can be called anything (versions,targetRevisions,etc)
  dev: HEAD
  staging: 0.1.3
  prod_client_1: 0.1.1
  prod_client_2: 0.1.2
```

> What would be your suggested algorithm for converting the structure of an appropriately formatted JSON/YAML file into parameters to substitute into template field Application?

How I imaging this is, the way we substitute the `template` parameters would remain similar to the current Git Files Generator 
but the changes would be required in the Generator's code to iterate over the version list and create an application for each environment mentioned.

**Comment by corradomatt** [comment]
This is similar to the functionality I'm looking for as well (but truth be told I haven't experimented with AppSets just yet). However we would supply different versions as well as different values per cluster. Currently we're using a custom plugin with ArgoCD that takes advantage of Helm and Helmfile where our directory structure looks like this...

```YAML
# envs
# ├── global
# │   └── values
# │       ├── app1.yaml
# │       └── app2.yaml
# ├── cluster1
# │   ├── workloads.yaml
# │   └── values
# │       ├── app1.yaml
# │       └── app2.yaml
# ├── cluster2
# │   ├── workloads.yaml
# │   └── values
# │       ├── app1.yaml
# │       └── app2.yaml
```

Our workloads.yaml file looks like...
```YAML
workloads:
  - chart: app1
    version: 1.0.0
  - chart: app2
    version: 1.1.0
```

The Helmfile plugin reads our Helmfile config to determine which version of the helm chart we want to deploy from the workloads.yaml file and then merges values from `global/values/<app>.yaml` and `cluster1/values/<app>.yaml` to produce the final values config to be passed to the chart.

Obviously this isn't the same use-case as gulativishwas mentions above but I thought I would mention it in case both use-cases could be covered in a single feature.

**Comment by rumstead** [comment]
@corradomatt if I am understanding correctly I think this is almost exactly what you have. I *think* this would work for you if you can put [helm parameters](https://argoproj.github.io/argo-cd/user-guide/helm/#build-environment) in the config file. 

I don't quite follow the 'merging' part but I could see a lot of value in having a default value that can be overridden. Ie, for a helm/kustomize parameter or a version. Then you would use the appsets to deploy to different clusters.

**Comment by corradomatt** [comment]
Thanks @rumstead I think it's similar to my use-case for sure but there might be challenges. For the merging of values we have global values that should be applied to all clusters for a particular app as well as values that are cluster specific which get merged before an ArgoCD sync. We could easily move those global values up to be chart defaults in our custom helm charts to cover that situation.

Where I'm not sure our use-case applies is that @gulativishwas mentions _only_ needing to modify the versions across different clusters. We need that option in addition to providing some custom helm chart values per cluster.

**Comment by rumstead** [comment]
Agreed. I would love to be able to do:

config.yaml/json:
```
cluster1:
   helmParameters:
       - name: image.version
          value: 1.1.1
```

**Comment by rumstead** [comment]
#173 Feels related as well. 

Another idea would be able to determine the git directory path based on a label/annotation from the cluster secret.

Assuming:
I have 3 clusters registered with ArgoCD. Each with a label/annotation called `cluster/name`.
1. dev-cluster -> `cluster/name: dev'
2. stage-cluster -> 'cluster/name: stage'
3. prod-1-cluster -> 'cluster/name: prod-1'

My GIT directory structure could look like this:
```
# ├── apps
# │   ├── app1
# │   │   ├── appset.yaml
# │   │   ├── dev
# │   │   │   └── config.yaml
# │   │   ├── stage
# │   │   │   └── config.yaml
# │   │   ├── prod-1
# │   │   │   └── config.yaml
``` 

Then the appset yaml could look something like this:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-appset
spec:
  generators:
      - clusters:
          path: apps/app1/'{{metadata.annotations/label.cluster/name}}'/config.yaml
          selector:
            matchLabels:
                 ....
...
```
Telling the cluster generator (or maybe a new one) where to look for the cluster-specific config file.

**Comment by rumstead** [comment]
@jgwest  @gulativishwas  @corradomatt curious about all your thoughts. we are looking to use something like this in the near future are happy to implement it once we have an agreed-upon solution.

**Comment by corradomatt** [comment]
I like the idea of cluster labels being used in the AppSet. I can't speak about my opinion overall because I have yet to play with the AppSet feature ... we're still using the standard Application controllers. I'm hoping to be able to start investigating AppSet within a week or so.

**Comment by gulativishwas** [comment]
@rumstead I also like the idea of the cluster labels being used. If we all agree, we should leverage the cluster labels like  `{{metadata.annotations.cluster/name}}` in possibly all the generators. 

This would make something like this possible as well (which would be handy to reduce the number of apps that matrix generator creates):
```
- matrix:
      generators:
        - git:
              repoURL: some-url
              revision: HEAD
              files:
              - path: "apps/app1/{{metadata.annotations.cluster/name}}/config.yaml"
        - clusters: 
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
```

**Comment by jgwest** [comment]
Hey all, so, it seems there are a few different ideas here being discussed here, which I thought I would individually tease out.

## Idea: 'Blueprint file format'

What I see being described here is something I might call a blueprint file: A file (or files), which live in Git, and which describe (in some fashion) how to create multiple Applications (with a minimum of data duplication). This is the concept is that this issue was originally opened for. 

So, unlike the Git file generator as it currently exists, which tends to be a single file that describes a single Application, here we have a single file that describes multiple Applications. 

Thus I use the analogy of a "blueprint", which is used to produce a set of Applications, rather than just for a single Application.

Anyone hate this analogy and have an alternative :smile: ? Any existing analogies in the Kubernetes/templating space that folks might already be familiar with, that we can borrow? Open to suggestions!


#### Idea of a blueprint file:
- A file format that can describes multiple permutations of an Application
    - File format aims to reduce duplication of application data (DRY)
- An algorithm, which takes files of that format as input, and outputs a set of key/value string parameters, to be substituted into the `template` field.
- One or more files, following this file format, would live in Git, and would be discovered via the Git file generator.
- The Git file generator would be responsible for locating these files, running the algorithm, and returning the generated Application parameters to the ApplicationSet templating functions.

Is this a fair, concise summary of this idea? 

#### Next steps for Blueprint file

Personally, I like this idea, it seems like a natural extension to existing Git file generator, and should be solving an issue that many users have. So let's continue the discussion of this idea, here, on this issue :+1: .

Mainly what I haven't yet seen proposed here is a proposal for a file format, and a corresponding algorithm to turn that file format into sets of parameters. 

I would also stress that this file format should be generic enough to work for many different user's use cases, not just your particular use case (I only mention this generally, I haven't carefully considered whether the existing examples provided do or not meet this criteria).

(Proposals/algorithms in the form of PRs are fine, BUT just be prepared to have to rewrite your PR if there is disagreement on the design!).

## Idea: Ability to pass JSON/YAML objects into ApplicationSet template fields (which AFAICT will likely require a new untyped template field)

Another idea I see touched on here is passing JSON/YAML objects into the `template`, rather than just individual string parameters.

This would be the ability, with the Git file generator, to pass a config.yaml like this (or equiv json):
```yaml
cluster:
   helmParameters:
     - name: image.version
       value: 1.1.1
```

and then have an ApplicationSet with a template like this:
```yaml
spec:
  # (...)
  template:
    spec:
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook

        helm:
          parameters: {{ cluster.helmParameters}}
```

Such that when the Application is generated for this ApplicationSet, the YAML object (described by the config.json) will be inserted into the appropriate spot in the Helm parameters:

```yaml
spec:
  # (...)
  template:
    spec:
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook

        helm:
          parameters: 
            - name: image.version
              value: 1.1.1
```

However, (this is getting into implementation details) but I suspect it will require us to introduce a new field, as an alternative to `template`, like this:

Elements []apiextensionsv1.JSON `json:"elements"`
```go
// ApplicationSetSpec represents a class of application set state.
type ApplicationSetSpec struct {
	Generators []ApplicationSetGenerator `json:"generators"` // old
	Template   ApplicationSetTemplate    `json:"template"` // old
	UntypedTemplate apiextensionsv1.JSON `json:"templateUntyped"` // new hotness
	SyncPolicy *ApplicationSetSyncPolicy `json:"syncPolicy,omitempty"` // old
}
```

producing:
```yaml
spec:
  # (...)
  templateUntyped:
    spec:
      source:
       helm: # (...)
```

There's most definitely a better name for it than 'untyped template', but that's the idea. Ideally there would be a way to use the existing `template` field for this, but I don't see a way: I don't want to lose the typed nature of the existing `template` field, and yet we will need to break that structure with this feature. 

#### Next step for insertion of yaml/json objects into untyped template

IMHO I think this should be moved to a separate issue, which I am happy to open. This idea has been generally proposed elsewhere, especially around how to insert values into Helm. (This would likely also be useful for the blueprint file format, but is NOT a prerequisite for implementing the blueprint, AFAICT).

## Substitution of parameters outside the template field

Finally, this was proposed as an interesting way to handle this issue:
```
spec:
  generators:
      - clusters:
          path: apps/app1/'{{metadata.annotations.cluster/name}}'/config.yaml
```

However, with the ApplicationSet controllers current design, parameters (`{{metadata.annotations.cluster/name}}` in the example above) may only be substituted into the `template` field (and child fields) of an ApplicationSet. In this case, the parameter is attempting to be inserted under `spec`, which will not work (at this time). 

I'm not against adding support for parameter substitution outside of the `template` field, but since this is a significant architectural change, we would want to make sure we have exhausted other potential options first.

## Conclusion

So, the above characterization is how I have interpreted and synthesized the various comments on this issue. Anyone disagree with characterization, and/or have any good holes to poke in my logic? Anything missing?
