### ISSUE TITLE
git fetch fails when running ArgoCD v2.1.0-rc2

### ISSUE THREAD

**Issue by rogfut** [argoproj-labs/applicationset#329]
## Issue Description
When running ArgoCD v2.1.0-rc2 with an ApplicationSet configured to pull from a private gitlab repo, the applicationset pod fails to run git fetch with fatal error 128.

A normal ArgoCD Application was able to git fetch from the same configured gitlab repo so the issue seems specific to ApplicationSet.

Downgrading ArgoCD to 2.0.5 resolved the issue.

## Repro Steps

1. configure a private gitlab repo in ArgoCD v2.1.0-rc2
2. create an ApplicationSet that points to the configured private repo in step 1
3. argocd-applicationset-controller throws error on git fetch

```
2021-08-03T21:41:05.107Z        ERROR   controller-runtime.manager.controller.applicationset    Reconciler error        {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "test-a", "namespace": "argocd", "error": "Error during fetching repo: `git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.rogerfutrell.com': No such device or address", "errorVerbose": "`git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.rogerfutrell.com': No such device or address\nError during fetching repo\ngithub.com/argoproj-labs/applicationset/pkg/services.checkoutRepo\n\t/workspace/pkg/services/repo_service.go:159\ngithub.com/argoproj-labs/applicationset/pkg/services.(*argoCDService).GetFilePaths\n\t/workspace/pkg/services/repo_service.go:59\ngithub.com/argoproj-labs/applicationset/pkg/generators.(*GitGenerator).generateParamsForGitFiles\n\t/workspace/pkg/generators/git.go:102\ngithub.com/argoproj-labs/applicationset/pkg/generators.(*GitGenerator).GenerateParams\n\t/workspace/pkg/generators/git.go:64\ngithub.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).generateApplications\n\t/workspace/pkg/controllers/applicationset_controller.go:349\ngithub.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).Reconcile\n\t/workspace/pkg/controllers/applicationset_controller.go:93\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:267
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99
```

## ArgoCD Version
v2.1.0-rc2
I dont have the full argocd version output because I reverted back to 2.0.5 to get applicationsets working again

## Additional Info
I tried uninstalling and reinstalling the applicationset controller, it made no difference

**Comment by jgwest** [comment]
HI @rogfut , I tried with latest Argo CD (v2.1.0-rc2) and latest ApplicationSet controller (v0.2.0 RC) and was able to add a private GitLab repo without any issues (both controllers were able to access it fine). 

Any more information you can provide to help reproduce the issue? (FWIW the address in the exception `https://gitlab.rogerfutrell.com` doesn't resolve for me, but I assume this is a private instance)

**Comment by EugeneLugovtsov** [comment]
The issue is reproduced with applicationsets v0.1.1. After updating to v0.2.0 everything work as a charm :)

**Comment by rogfut** [comment]
Thanks @EugeneLugovtsov, it looks like I was running Applicationsets v 0.1.0.  I'll try again with argocd v2.1.0-rc2 and applicationset v0.2.0  when I get the chance.

@jgwest Sorry the repro info was minimal, I blew away the install by reverting to argocd 2.0.5 to unblock myself before logging the bug.  If you are interested I can setup another repro of ArgoCD v2.1.0-rc2 and ApplicationSet v0.1.0 and provide more detail if they are supposed to be compatible.  A little bit more info on the repro from memory:

- ArgoCD v2.1.0-rc2
- ApplicationSet v0.1.0
- `https://gitlab.rogerfutrell.com` is a private on-prem gitlab repo.  DNS wont resolve external to my network.
- A Basic ArgoCD Application created via GUI using the same repo url worked, ApplicationSet v0.1.0 did not.
- the git fetch was failing in the applicationset-controller pod

### Yaml that was applied to reproduce the failure
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: "https://testcluster.k8s.rogerfutrell.com:8443"
    argocd.argoproj.io/sync-options: PruneLast=true
  creationTimestamp: null
  name: test-a
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: test-a environment
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: test-a
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: argocd/apps/**/test-a/config.json
      repoURL: https://gitlab.rogerfutrell.com/devops/k8s-iac.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ appName }}'
      name: test-a-{{ userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: '{{ destNamespace }}'
        server: '{{ destServer }}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: test-a
      source:
        path: '{{ srcPath }}'
        repoURL: '{{ srcRepoURL }}'
        targetRevision: '{{ srcTargetRevision }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
status: {}
```


### ApplicationSet version
Not sure the best way to show the version, hopefully this suffices
```
 k get pod argocd-applicationset-controller-76fc4dc766-xz5d2 -n argocd -o yaml | grep image
            f:image: {}
            f:imagePullPolicy: {}
    image: quay.io/argocdapplicationset/argocd-applicationset:v0.1.0
    imagePullPolicy: Always
    image: quay.io/argocdapplicationset/argocd-applicationset:v0.1.0
    imageID: docker-pullable://quay.io/argocdapplicationset/argocd-applicationset@sha256:bd62ff6ee18f16e9021ae89e347cd6ded960d6054bdd3c608fc05acdf8a03bc3
```
