### ISSUE TITLE
generate unique key for each application base on a salt

### ISSUE THREAD

**Issue by obeyler** [argoproj-labs/applicationset#330]
feature proposal
I'm looking for a way to create unique password for each application deployed by application set.
by example a nice way could be
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          project: defaut
  template:
    metadata:
      name: '{{name}}-my-app'
    spec:
      project: '{{values.project}}'
      source:
        repoURL: myGitrepo
        targetRevision: HEAD
        path: applications/my-app
        helm:
          releaseName: test
          parameters:
            - name: bucket
              value: '{{name}}'
            - name: password
              value: '{{name + salt | md5sum}}'
      syncPolicy:
        automated: { }
        syncOptions:
          - CreateNamespace=true
      destination:
        server: '{{server}}'
        namespace: test
```
I already use argo-vault-plugin to get salt value so at the end it should be like:
value: '{{name + salt | md5sum}}' => value: '{{name +<path:kv/data/global/#salt> | md5sum}}'
