### ISSUE TITLE
Remove mandatory fields in list generators

### ISSUE THREAD

**Issue by benjamin-bergia** [argoproj-labs/applicationset#335]
In the current list generator, cluster and url are mandatory fields. This doesn't seem to make much sense since it is already covered by the cluster generator. Unfortunately there is currently no way to use the list generator to pass a list of arbitrary objects.
For example, I would like to pass a list of application names since my repository doesn't play well with the current implementation of the git directory generator. I would like to do the following:
```yaml
spec:
  generators:
    - list:
        elements:
          - application: test-a
          - application: test-b
 ```
Which is currently not supported. I have a single cluster and if I had more than one I would probably try to use a matrix generator with a list + cluster generator.

To me the current list generator duplicate the features from other generators and doesn't bring much. Having a generic generator that provide a list of arbitrary objects, in an other hand, opens a whole new range of solutions and can be used when other generator fall short.
