### ISSUE TITLE
Support "any", "one" filters

### ISSUE THREAD

**Issue by rtnpro** [argoproj-labs/applicationset#34]
I see that `Only` or `Any` functions are supported in the https://github.com/antonmedv/expr library. We have a use case for using `Only` and `Any` in ApplicationSet `generator` filters.

We have multiple Kubernetes clusters per environment. Sometimes, we'd like to run our workloads, e.g., Cronjobs, only on one of the available clusters in the environment. An `any`, `one` filter will be super helpful here.

**Comment by OmerKahani** [comment]
@rtnpro can you please add an example applicationset YAML that solves your use case?

**Comment by rtnpro** [comment]
Let's say I have multiple staging and production clusters clusters, how do we deploy a workload only to a cluster in a environment. I had tried to brainstorm patterns to get this working, using `one`, `any`, etc. functions, but could not come up with a satisfactory pattern. Also, `one` function of `expr` library does not behave the way I expected it to. It returns `True` only if there's only one element matching the predicate. I was expecting it to return `True` the first item among many matching the predicate.


**Example clusters**

```
{ 
  "aws_account": "123456", 
  "asset_id": "11223344", 
  "cluster": {
    "owner": "cluster-admin@company.com", 
    "name": "staging-01",
    "address": "http://1.2.3.4"
  },
  "metadata": {
    "labels": {
      "environment": "staging"
    }
  }
}
```

```
{ 
  "aws_account": "123456", 
  "asset_id": "11223345", 
  "cluster": {
    "owner": "cluster-admin@company.com", 
    "name": "staging-02",
    "address": "http://1.2.3.5"
  },
  "metadata": {
    "labels": {
      "environment": "staging"
    }
  }
}
```

```
{ 
  "aws_account": "123457", 
  "asset_id": "11223350", 
  "cluster": {
    "owner": "cluster-admin@company.com", 
    "name": "production-01",
    "address": "http://1.2.4.4"
  },
  "metadata": {
    "labels": {
      "environment": "production"
    }
  }
}
```

```
{ 
  "aws_account": "123457", 
  "asset_id": "11223351", 
  "cluster": {
    "owner": "cluster-admin@company.com", 
    "name": "production-02",
    "address": "http://1.2.4.5"
  },
  "metadata": {
    "labels": {
      "environment": "production"
    }
  }
}
```

The generator and filter I was envisioning would look like

```
  - git:
      repoURL: https://github.com/infra-team/cluster-deployments.git
      files:
        - path: config/*.json
      filters:
        - expr: '{{ metadata.labels.environment in ['production', 'staging']}}'
        - one:
          - expr: '{{ metadata.lables.environment == 'production' }}'
          - expr: '{{ metadata.labels.environment == 'staging' }}'
```

What I am looking for is to select a single cluster in each environment, so that I don't need to add multiple generators with slightly varying filters. But, there are some semantic challenges here. 

From UX standpoint for the ApplicationSet spec, I'd prefer to put `one` inside `filters`, as we are using it to filter the list of clusters generated. But, `one` and `filter` are both functions in `expr` library, so including `one` inside `filters` looks a bit odd.

I feel that we do not have the required feature in the `expr` library to achieve what I have been trying to do. A crude workaround will be to just add a `label` to clusters to ensure that only one cluster in an environment has that label enabled. Then, we can filter by that `label`.

Let me know what you think @OmerKahani
