### ISSUE TITLE
Support 'union' generator

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/applicationset#344]
# Summary 

Support generator that allows to "union" several generators and override output of one generator with values of another generator.

The new generator is supposed to solve the following use cases: 
* User wants to install the same application into all clusters with default parameters but override some parameters in couple clusters
* User wants to install the same application into all clusters but split clusters into "waves". Each wave will have couple of different parameters

# Proposal

Introduce `union` generator that allows specifying list of sub-generators and list of merge keys. The new generator should unite output of merge generators. The merge keys should be taken into account to detect duplicates and override values:

Example:

```
 generators:
  - union:
      mergeKeys: # specifies which keys should be used to detect duplicates and apply overrides
      - url 
      generators:
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
              matchExpressions:
                - {key: cluster.name, operator: NotIn, values: [excluded-cluster]} # matchExpressions should allow to exclude clusters
            values: # default values for all clusters
              install-kafka: true

        - items:
            elements:
              cluster: engineering-dev
            values: # overrides for dev
              install-kafka: false

```
