### ISSUE TITLE
Cluster generator cannot select local cluster

### ISSUE THREAD

**Issue by mgoodness** [argoproj-labs/applicationset#35]
The cluster generator currently requires a Kubernetes Secret to exist for each cluster. Argo CD doesn't use a Kubernetes Secret to identify the local cluster the way it does "external" clusters, so it can't be selected.

The easy workaround is to manually create a K8s Secret with the required `argocd.argoproj.io/secret-type=cluster` annotation and populate it with:

```
data:
  name: in-cluster
  server: https://kubernetes.default.svc
```

That Secret can then be annotated and labeled like any other, and the cluster-generator can use those values for templating.

However, that doesn't feel like a good solution in terms of usability.

**Comment by mgoodness** [comment]
This is exactly what I'm doing pending a better solution:

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-local
  namespace: argocd
stringData:
  config: '{"bearerToken":"","tlsClientConfig":{"insecure":false,"caData":""}}'
  name: in-cluster
  server: https://kubernetes.default.svc
type: Opaque
```
