### ISSUE TITLE
add ability to modify template variable

### ISSUE THREAD

**Issue by r0bj** [argoproj-labs/applicationset#351]
It would be helpful to be able to use some filters on template variables, similar to helm template replace: `myapp-{{ $cluster | replace "_" "-" }}`.

Example ApplicationSet:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  generators:
  - list:
      elements:
      - cluster: on-prem1
      - cluster: gke_myproject_us-west1-a_c1
  template:
    metadata:
      name: 'myapp-{{cluster}}'
    spec:
      project: default
      source:
        path: apps/myapp
        repoURL: git@github.com:myorg/apps.git
        targetRevision: HEAD
      destination:
        name: '{{cluster}}'
        namespace: prod
```
It generates error:
```
2021-08-24T01:11:20.992Z	ERROR	controller-runtime.manager.controller.applicationset	Reconciler error	{"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "myapp", "namespace": "argocd", "error": "Application.argoproj.io \"myapp-gke_myproject_us-west1-a_c1\" is invalid: metadata.name: Invalid value: \"myapp-gke_myproject_us-west1-a_c1\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214
```

GKE clusters use underscore in cluster names. Using those clusters in list generator is failing due to usage of not allowed characters. If we could use some sort of variable filter to replace characters (e.g. similar to jinja2 or helm template filters `myapp-{{ $cluster | replace "_" "-" }}`) we could cover those use cases.
