### ISSUE TITLE
Gracefully handle application validation errors

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/applicationset#356]
# Summary

Application set validates generated applications (which is good) but refuses to create any application even if only one of the generates apps is invalid. Instead, the controller should generate valid applications and skip only invalid ones.

Here is a sample use case where current behavior causes confusion. 
* App set generates an application that references cluster A
* Generator source has changes so now app set produces 2 applications and Cluster A got removed from Argo CD.
* Controller detects the error in the first A (since cluster no longer registered) 
* User assuming that something is wrong with new application and does not know how to fix the issue

# Proposal 

Two changes are proposed:

* Application Set controller should generate valid applications and skip only invalid once
* The applications generation error should be reported in `status.conditions` field of the ApplicationSet CR:

```yaml
status:
  conditions:
    type: ApplicationsGenerated
    status: False
    reason: ApplicationValidationFailed
    message: Cluster A is not registered
```
