### ISSUE TITLE
Fix resource name length issues with generated applications.

### ISSUE THREAD

**Issue by dgoodwin** [argoproj-labs/applicationset#36]
At present it is extremely easy to hit resource name length issues with generated applications. We will need to come up with a strategy to effectively truncate and randomize them if they exceed the 253 chars kube resources are limited to.

Additionally we need to watch out for labelling as these are even more restricted, both key and value limited to 63. (assuming we use labels to map applications back to the appset they originated from)

**Comment by dgoodwin** [comment]
A proposal for discussion: 

Assume we start with base name of {appsetname}-{generatoritemname}.

All generators would be required to provide some kind of a name for each matching Application. For clusters we could use the cluster name. For git discovery probably the matching folder name. For git files we require a name property in each list row. And similar for the ApplicationSet inline list items.

We use that full concatenated name if it's not too long, and if it is we fall back to something like this, which is how we solved this problem in one of my team's projects: https://github.com/openshift/hive/blob/master/pkg/apis/helpers/namer.go#L15

**Comment by dgoodwin** [comment]
I discovered the cluster generator was using the Secret name for the "name" templating, which can be quite long. (i.e. cluster-api.mycluster.mydomain.openshift.com-3927666468). I've opened #41 to fix this to use the name Argo has instead and that will help avoid this problem.

However it still is going to be quite possible to hit depending on the kubeconfig context name and template name.

**Comment by mgoodness** [comment]
My environment is exactly the opposite, with most Secret names being considerably shorter than the contexts. I know there's other work being done around cluster naming, though, so this strikes me as a reasonable change.

**Comment by mgoodness** [comment]
Agree that we need to address the application name & label length issue, but I'd like to do it in such away that end-users (like me) can still provide their own templates for naming:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-services-internal-ingress-nginx
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions: [...]
  template:
    metadata:
      labels:
        app: internal-ingress-nginx
        cluster: '{{metadata.labels.cluster}}'
        env: '{{metadata.labels.env}}'
        org: '{{metadata.labels.org}}'
        region: '{{metadata.labels.region}}'
      name: 'cluster-services-iin-{{metadata.labels.org}}-{{metadata.labels.env}}-{{metadata.labels.region}}-{{metadata.labels.cluster}}'
      namespace: argocd
    spec: {...}
```

Note that I'd love to do something like `'{{appset.name}}-{{metadata.labels.org}}-{{metadata.labels.env}}-{{metadata.labels.region}}-{{metadata.labels.cluster}}'`, but in this case had to truncate `-internal-ingress-nginx` to `-iin` because a number of my generated applications names would exceed the 63-character limit for labels.
