### ISSUE TITLE
Clusters with underscore in name causing problem with variable templating

### ISSUE THREAD

**Issue by r0bj** [argoproj-labs/applicationset#364]
Clusters with underscore in name causing problem with variable templating.

Example.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'myapp-{{name}}'
    spec:
      project: default
      source:
        path: apps/myapp
        repoURL: git@github.com:myorg/apps.git
        targetRevision: HEAD
      destination:
        name: '{{name}}'
        namespace: prod
```

Everything work fine unless cluster name consist underscore, e.g. `gke_myproject_us-west1-a_cluster1` (similar to how GKE clusters are named). In this case applicationset controller generates error message:
```
time="2021-09-02T21:09:13Z" level=error msg="error occurred during application generation: application destination spec is invalid: unable to find destination server: there are no clusters with this name: gke-myproject-us-west1-a-cluster1"
```

So it seems that applicationset controller replaced "_" to "-" in cluster name but now variable {{name}} is somehow broken, it is no longer store valid cluster name. So using that variable as a destination cluster is no longer works.

Maybe instead of modifying variable {{name}} by controller we can add new variable e.g. {{nameNormalized}} and leave {{name}} unchanged? It would give more transparency and predictability to the process.
