### ISSUE TITLE
Proposal: Allow variable interpolation in generator `values` field

### ISSUE THREAD

**Issue by Sinjo** [argoproj-labs/applicationset#371]
# Context

While using the cluster generator, we recently ran into a situation where being able to template the contents of the `values` map based on the parameters of each cluster.

The specific situation was that we wanted to make it possible for devs to opt into deploying an environment-specific image from a branch, somewhat like [this example from the docs](https://github.com/argoproj-labs/applicationset/blob/0edd1527bb73fa3c8e8578a1a6124e71412f5403/docs/Generators-Cluster.md#pass-additional-key-value-pairs-via-values-field), but where the environment and branch are per-developer.

For anyone not opted in, they hit a different `selector` and fall back to images built from the `main` branch.

# Current workaround

Ideally, we would be able to construct the image URL as a value based on the cluster parameters (we're using the environment name for it). That would make it easy to supply a different, hardcoded value of `main` for any deployments that aren't opted into environment-specific images.

The workaround we're currently using is to have different [generator templates](https://github.com/argoproj-labs/applicationset/blob/85f8d904cadb9595656dd12c312310ef00a27099/docs/Template.md#generator-templates) on the two selectors, which leads to a fair amount of duplication due to the way the merge algorithm works.

# Proposal

We would like to add the same parameter templating that's available in in the `template` itself to the map values in the `values` key of the selector. Running with [the example](https://github.com/argoproj-labs/applicationset/blob/0edd1527bb73fa3c8e8578a1a6124e71412f5403/docs/Generators-Cluster.md#pass-additional-key-value-pairs-via-values-field) from the cluster generator docs, it would look something like:

```yaml
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          type: 'dev'
      # A key-value map for arbitrary parameters
      values: 
        revision: "dev-{{metadata.labels.environment}}" # dev clusters use per-environment branches
  - clusters:
      selector:
        matchLabels:
          type: 'staging'
      # A key-value map for arbitrary parameters
      values: 
        revision: HEAD # staging clusters use HEAD branch
  - clusters:
      selector:
        matchLabels:
          type: 'production'
      values: 
        # production uses a different revision value, for 'stable' branch
        revision: stable
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        # The cluster values field for each generator will be substituted here:
        targetRevision: '{{values.revision}}'
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: guestbook        
```

---

If you're on board with the idea, I'm happy to go ahead and put a PR together that adds this functionality to the controller!
