### ISSUE TITLE
A way to get path directories for git generator

### ISSUE THREAD

**Issue by Roshick** [argoproj-labs/applicationset#374]
As my setup heavily relies on paths in a repository (i.e. {project}/{namespace}/{application}.yaml) it would be awesome to have access to either a more powerful template engine (sprig with text/template instead of fasttemplate) or built in parameters I can access to get the names of each subdirectory and the filename without extension.

I could put this information into the yaml as well, but I feel like this defeats the purpose of having any directory structure and possibly leads to diverging information in the long run.

**Comment by Roshick** [comment]
An example of how I would think it could look like:

```
generators:
  - fan:
      in:
        git:
          repoUrl: someUrl
          revision: HEAD
          directories:
            - path: projects
      out:
        matrix:
          generators:
            - git:
                repoUrl: someUrl
                revision: HEAD
                files:
                  - path: projects/{{path.basename}}/clusters/*
            - git:
                repoUrl: someUrl
                revision: HEAD
                files:
                  - path: projects/{{path.basename}}/applications/*  
```
