### ISSUE TITLE
Allow regex capture groups in directories from git generation 

### ISSUE THREAD

**Issue by jkroepke** [argoproj-labs/applicationset#377]
Hi,

I have a git contains multiple releases contains kustomize:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-deploy-dev
spec:
  generators:
    - git:
        repoURL: git@github.com:org/app-deploy.git
        revision: HEAD
        directories:
          - path: 'app-*'
  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      project: default
      source:
        repoURL: git@github.com:org/app-deploy.git
        targetRevision: HEAD
        path: '{{path}}/overlays/dev'
      destination:
        server: https://kubernetes.default.svc
```

But while dev is always available, other environment like qa are not available in early stages. This results into a lot of Application that going to be errored.

Switch to 

```yaml
        directories:
          - path: 'app-*/overlays/dev'
```

May not help, since `{{path.basename}}` would always dev now. Losing the information like the service name.

A solution could be allowing the capture group inside path and expose the groups as variable:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-deploy-dev
spec:
  generators:
    - git:
        repoURL: git@github.com:org/app-deploy.git
        revision: HEAD
        directories:
          - path: '(app-*)/overlays/dev'
  template:
    metadata:
      name: '{{path.match.1}}-dev'
    spec:
      project: default
      source:
        repoURL: git@github.com:org/app-deploy.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
```
