### ISSUE TITLE
anything i missed ?

### ISSUE THREAD

**Issue by pyfs** [argoproj-labs/applicationset#378]
argocd & argocd applicationset installed as documented, ApplicationSet CRD found, but there's no argocd application created; at the same time, `argocd-applicationset-controller` has nothing usefull log to ref.

```shell
NAMESPACE↑         NAME                    AGE   
default            guestbook               19h
```
![image](https://user-images.githubusercontent.com/67151035/134797856-55aea5a6-ed05-4b2d-94d2-670d5a25b3ee.png)

>  ### *actions i did as below, is there anything that i missed?*

---
installing
```shell
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.2.0/manifests/install.yaml
```

Current Version:

```shell
argocd: v2.1.2
application-set: v0.2.0
```

ApplicationSet CRD as Readme shows:

```yaml
# This is an example of a typical ApplicationSet which uses the cluster generator.
# An ApplicationSet is comprised with two stanzas:
#  - spec.generator - producer of a list of values supplied as arguments to an app template
#  - spec.template - an application template, which has been parameterized
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {} # This is a generator, specifically, a cluster generator.
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: guestbook

```

**Comment by jgwest** [comment]
May want to check that the `ApplicationSet` you are creating is being created in the same directory as Argo CD, usually `argocd`. It couldn't hurt to check the applicationset controller logs as well.

**Comment by pyfs** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd   # here is the missed pattern
spec:
```
---

Thank you for help ! 👍  + 1024
