### ISSUE TITLE
Matrix generator (Git + List) not working as expected

### ISSUE THREAD

**Issue by schlapzz** [argoproj-labs/applicationset#384]
I'm trying to get the matrix generator working with the Git Directory and the List generator

I try to achieve following result:
* repository with 2 directories, containing a deployment for producer / consumer app (Git directory generator)
* Two namespaces for dev/prod (List generator)

The Git structure is as follow:
```
consumer
└─ consumer.yaml
producer
└─ producer.yaml   
```

Here is my ApplicationSet Manifest:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-example
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
              - cluster: dev
                url: https://kubernetes.default.svc
              - cluster: prod
                url: https://kubernetes.default.svc
          - git:
              repoURL: https://github.com/schlapzz/argocd-applicationset.git
              revision: HEAD
              directories:
                - path: producer/
                - path: consumer/
  template:
    metadata:
      name: 'as-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/schlapzz/argocd-applicationset.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'application-set-{{cluster}}'
```

Expected ouput after the matrix generator:

```
- name: as-producer
  path: producer/
  path.basename: producer
  namespace: application-set-dev

- name: as-consumer
  path: consumer/
  path.basename: consumer
  namespace: application-set-prod

- name: as-producer
  path: producer/
  namespace: application-set-dev

- name: as-consumer
  path: consumer/
  path.basename: consumer
  namespace: application-set-prod

```

But instead of that, the ApplicationSet Controller is not creating any Applications. Here is the log ouptut of the ApplicationSet Controller

```
time="2021-10-04T07:16:40Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_schlapzz_argocd-applicationset operation_name="exec git" time_ms=1.4357149999999999
time="2021-10-04T07:16:40Z" level=info msg="applications result from the repo service" allPaths="[consumer producer]" repoURL="https://github.com/schlapzz/argocd-applicationset.git" revision=HEAD total=2
time="2021-10-04T07:16:40Z" level=info msg="generated 0 applications" generator="{<nil> <nil> <nil> 0xc000801760 <nil> <nil>}"
```

Any idea what is missing?
