### ISSUE TITLE
Support a cluster corresponding to a mirror warehouse

### ISSUE THREAD

**Issue by zhengyansheng** [argoproj-labs/applicationset#396]
I hope to support such a scenario. A cluster corresponds to an image warehouse address. Do you want to support such requirements in the future

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
        imageRegistry: xxx-registry.cn-beijing.cr.aliyuncs.com/dev
     - cluster: engineering-prod
       url: https://kubernetesxxx.default.svc
       imageRegistry: ccr.ccs.tencentyun.com/prod
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
```
