### ISSUE TITLE
Applicationset controller private repo constant unauthenticated requests

### ISSUE THREAD

**Issue by ddevaal** [argoproj-labs/applicationset#418]
We are running Kubernetes 1.22.2 on Azure with ArgoCD v2.1.6+a346cf9 and ArgoCD ApplicationSet 0.2.0. We are seeing many unauthenticated requests coming from the applicationset controller pod to our on-prem Gitlab instance. 

ip - - [17/Nov/2021:09:34:12 +0100] "GET /operations/infrastructure.git/info/refs?service=git-upload-pack HTTP/2.0" 401 26 "" "git/2.30.2"
ip - - [17/Nov/2021:09:34:13 +0100] "GET /operations/infrastructure.git/info/refs?service=git-upload-pack HTTP/2.0" 401 26 "" "git/2.30.2"

I have no clue why. I'm not seeing anything weird in the applicationset controller container logs. Only info logging, with git fetches etc that succeed perfectly. No errors or warnings. 

We have added the repository secret that ArgoCD also uses. It's like the applicationset controller first does an unauthenticated request and then an authenticated one.

What am I missing here? ArgoCD has no problem with the repository secret and ArgoCD ApplicationSet also succeeds but it's also dossing our Gitlab server with unauthenticated requests.

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: dev project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: dev
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/**/dev/config.json
      repoURL: https://git.domain.com/operations/infrastructure.git
      revision: HEAD
  syncPolicy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ appName }}'
      name: dev-{{ userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: '{{ destNamespace }}'
        name: '{{ clusterName }}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: dev
      source:
        path: '{{ srcPath }}'
        repoURL: '{{ srcRepoURL }}'
        targetRevision: '{{ srcTargetRevision }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
status: {}
```

config.json

```
{"appName":"app","userGivenName":"app","destNamespace":"somes","clusterName":"dev-domain-weu-aks","srcPath":"apps/api/overlays/dev","srcRepoURL":"https://git.domain.com/operations/infrastructure.git","srcTargetRevision":"","labels":null}
```

secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://git.domain.com/operations/infrastructure.git
  username: argocd
  password: asdkalsjdlaksjdlas
```
