### ISSUE TITLE
can we automate Deploy code in repo in a namespace with the same name as the branch

### ISSUE THREAD

**Issue by nishit93-hub** [argoproj-labs/applicationset#420]
Hi All,

Can we automate this `Deploy code in repo in a namespace with the same name as the branch`

**Comment by vavdoshka** [comment]
@nishit93-hub 
the easiest example could be

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-approot
spec:
  generators:
  - scmProvider:
      cloneProtocol: https
      gitlab:
        group: "acme/myrepo"
        allBranches: true
        tokenRef:
          secretName: gitlab-token
          key: token
  template:
    metadata:
      name: {{ repository }}.{{ branch }}
    spec:
      project: default
      source:
        repoURL: {{ url }}
        targetRevision: {{ branch }}
        path: "helm-charts"
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ branch }}
```

and this can be customized further to have also some filtering on branch naming:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-approot
spec:
  generators:
  - scmProvider:
      cloneProtocol: https
      gitlab:
        group: "acme/myrepo"
        allBranches: true
        tokenRef:
          secretName: gitlab-token
          key: token
      filters:
        - branchMatch: branch1
        - branchMatch: branch2
  template:
    metadata:
      name: {{ repository }}.{{ branch }}
    spec:
      project: default
      source:
        repoURL: {{ url }}
        targetRevision: {{ branch }}
        path: "helm-charts"
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ branch }}
```

check more on [SCM provider](https://github.com/argoproj-labs/applicationset/blob/master/docs/Generators-SCM-Provider.md)
note that `ApplicationSet` itself should be deployed in the same namespace where ArgoCD is.

**Comment by nishit93-hub** [comment]
@vavdoshka , Hi Thanks for sharing.

Will these `{{ repository }}.{{ branch }}` `{{ url }}` `{{ branch }}` gets automatically updated once developer creates new branch and commit some changes.?

**Comment by vavdoshka** [comment]
@nishit93-hub 
yes, ArgoCD ApplicationSet Controller checks the repository periodically and would submit as many ArgoCD applications as there are branches in the repo, it also will remove the application from ArgoCD if it won't find a correspondent branch. 

However, the actual deployment of K8s manifests is controlled by ArgoCD itself, so if you also want the created Applications to deploy manifests automatically you need to slightly adjust the Application template.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-approot
spec:
  generators:
  - scmProvider:
      cloneProtocol: https
      gitlab:
        group: "acme/myrepo"
        allBranches: true
        tokenRef:
          secretName: gitlab-token
          key: token
  template:
    metadata:
      name: {{ repository }}.{{ branch }}
    spec:
      project: default
      source:
        repoURL: {{ url }}
        targetRevision: {{ branch }}
        path: "helm-charts"
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ branch }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
        automated: 
          prune: true
          allowEmpty: true
          selfHeal: true
```

In this case, you will get the application created once a branch is created, then ArgoCD will deploy the manifests automatically, and then if there will be any new commits in the same branch ArgoCD will deploy/remove manifests to match with the desired state as well.
