### ISSUE TITLE
Cannot template syncPolicy parameters because of applicationset validation

### ISSUE THREAD

**Issue by jemag** [argoproj-labs/applicationset#424]
In the optics of self-serve, I would like to let each team specify their "prune" and "selfHeal" parameters from syncPolicy. To do so, I am using the following applicationset:
```yaml
apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: XX-bootstrap
    namespace: argocd
    annotations:
      argocd.argoproj.io/sync-options: Validate=false
  spec:
    generators:
    - git:
        repoURL: "somegitrepo"
        revision: HEAD
        files:
        - path: apps/dev/**/config.yaml
    template:
      metadata:
        name: "XX-{{app.name}}"
      spec:
        project: XX
        source:
          repoURL: "somegitrepo"
          targetRevision: HEAD
          path: "{{app.path}}"
        destination:
          server: https://kubernetes.default.svc
          namespace: XX
        syncPolicy:
          automated:
              allowEmpty: true
              prune: "{{app.sync.prune}}"
              selfHeal: "{{app.sync.selfHeal}}"
```
The problem arises because "{{app.sync.prune}}" is not a boolean but rather a string:
![image](https://user-images.githubusercontent.com/7985687/143610597-4ba58a25-8f97-4303-8d27-3cbc3a269ef4.png)

I also cannot remove the double quotes, since my applicationset passes through kustomize. Therefore using the form {{app.sync.prune}} would result in 
`Error: map[string]interface {}(nil): yaml: invalid map key: map[string]interface {}{"app.sync.prune":""}`

As you can see in the yaml above, I also tried to disable the validation using 
```yaml
annotations:
      argocd.argoproj.io/sync-options: Validate=false
```
however that did not seem to help.

**Comment by olvesh** [comment]
Have you tried omitting the quotes around the templated values?
I.e.
```
              prune: {{app.sync.prune}}
              selfHeal: {{app.sync.selfHeal}}
```
Your syntax-checker will probably be red, but it might just work :-)

**Comment by jemag** [comment]
As mentioned in the original post, I cannot because it will cause problems with kustomize:
> I also cannot remove the double quotes, since my applicationset passes through kustomize. Therefore using the form {{app.sync.prune}} would result in
Error: map[string]interface {}(nil): yaml: invalid map key: map[string]interface {}{"app.sync.prune":""}

**Comment by ekbduffy** [comment]
@olvesh 
> Have you tried omitting the quotes around the templated values?

I even tried this on kubectl apply - doesn't work, since it's still being converted to JSON, and during conversion {{anything here}} being failed with error like:

> invalid map key: map[interface {}]interface {}{"prune":interface {}(nil)}

**Comment by ekbduffy** [comment]
Looks like now the only solution is to annotate for non-deletion each separated resource created by the application definition. [https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-prune-resources](Here's the doc for it)

**Comment by brunocascio** [comment]
Is there any plan to support this feature? :(
it's a quite common scenario. For example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: lab-nonprod
            prune: true
            selfHeal: true
          - environment: qa
            cluster: lab-nonprod
            prune: true
            selfHeal: false
  template:
    metadata:
      name: 'bookinfo-{{environment}}'
    spec:
      project: "bookinfo"
      source:
        repoURL: https://myrepo.com/k8s-template-deployment.git
        targetRevision: HEAD
        path: '.deploy/kustomize/overlays/{{environment}}'
      destination:
        name: '{{cluster}}'
        namespace: 'project-bookinfo-{{environment}}'
      syncPolicy:
        automated:
          prune: '{{prune}}'
          selfHeal: '{{selfHeal}}'
        syncOptions:
          - CreateNamespace=true
```
