### ISSUE TITLE
Git generator: removal of Helm Chart causes error message and no application deletion

### ISSUE THREAD

**Issue by alexanderdalloz** [argoproj-labs/applicationset#431]
We are using the Git generator, provisioning all Argo CD projects and applicationsets through a standardized Helm Chart.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  generators:
  - git:
      directories:
      - path: '*'
      repoURL: ssh://git@reposerver:7999/opsrepos/opsrepo_project-stage.git
      revision: stages/etu
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
```
The templated project definition looks like this (as well just a part of it quoted):
```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: project-etu
  destinations:
  - namespace: project-etu
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: ""
    kind: ResourceQuota
  orphanedResources:
    warn: false
```
The application CR has set the
```
  finalizers:
  - resources-finalizer.argocd.argoproj.io
```
metadata as well. And sync options are defined as:
```
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - preserveResourcesOnDeletion=false
```

Now when deleting a directory with a previously Argo CD deployed Helm Chart from within the source git repo leads to the error message within Argo CD
`'rpc error: code = Unknown desc = Manifest generation error (cached): airflow-helm: app path does not exist'`
The application does not get deleted. We expect it would be deleted.
