### ISSUE TITLE
Add the ability to exclude files when using the git file generator

### ISSUE THREAD

**Issue by adamjohnson01** [argoproj-labs/applicationset#468]
When using the git directory generator it is possible to exclude specific paths like this

```  generators:
  - git:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      revision: HEAD
      directories:
      - path: examples/git-generator-directory/excludes/cluster-addons/*
      - path: examples/git-generator-directory/excludes/cluster-addons/exclude-helm-guestbook
        exclude: true
```

When using the git file generator I would like to be able to add files using a wildcard and then exclude specific files like this

```
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj-labs/applicationset.git
      revision: HEAD
      files:
      - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
      - path  "examples/git-generator-files-discovery/cluster-config/staging/config.json"
        exclude: true
```

Of course if there is another way to do this that I am not aware of then I would be happy to use that. If not I am also happy to implement this change if it is agreed.
