### ISSUE TITLE
ApplicationSet which generates Applications with matching names should report an error and return

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#68]
As of this writing, the `generateApplications` method does not check for applications with duplicate names, and thus multiple generated Applications may use the same name.

As discussed in the comments of the design proposal, this should be reported as an error:
> Two application with the same name would be considered an error. In this case error would be saved in status as an error condition.

### To reproduce:

Apply the following YAML, and observe that it reports `generated 3 applications`, even though only 1 Application resource is created:
```yaml
# The list generator specifies a literal list of argument values to the app spec template.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://1.2.3.4
      - cluster: engineering-prod
        url: https://2.4.6.8
      - cluster: finance-preprod
        url: https://9.8.7.6
  template:
    metadata:
      name: 'matching-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/jgwest/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
```

In this case, 0 applications should be generated, and an error should be reported in the ApplicationSet status conditions.
