### ISSUE TITLE
ApplicationSet should report error conditions/status based on the result of generator/template resuls

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#71]
When the user-provided generator/template produce invalid Argo CD `Application`s, we should note that error in the ApplicationSet CRD status field. See Argo CD's `ApplicationStatus` [conditions field](https://github.com/argoproj/argo-cd/blob/1ef14dca839423fe3cd9fade82bd1b3ed80eb5bd/pkg/apis/application/v1alpha1/types.go#L491).

Likewise I'm sure there are other status fields/conditions that would be useful to expose as part of an `ApplicationSet` `status` subtype.

Once implemented, one such function that would benefit from this is:
https://github.com/argoproj-labs/applicationset/issues/68

**Comment by OmerKahani** [comment]
Hi, what do you think about this structure (based on argocd ApplicationStatus)
```
status:
  applications:
    - name:
      lastSync:
      condition:
        - type:
          message:
          LastTransitionTime
```

**Comment by jgwest** [comment]
The way that Argo CD does conditions actually seems counter to current best practices around conditions: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

The API conventions page suggests the following condition fields:
```yaml
conditions:
  - type:  # Example: ErrorOccurred / ParametersGenerated / TemplateRendered
    status: # True/False/Unknown
    reason: # Single word camelcase representing the reason for the status eg MissingParameter or ErrorOccurred
    message: # Human readable message or error
    lastTransitionTime: # When this value last changed.
```

In addition to having conditions for each application, as you suggested, we can also have a conditions field at root the `status:` level too. This lets us communicate errors that aren't specific to particular applications. See the examples below.

This simulates an ApplicationSet with a single Application that failed on rendering the template:
```yaml
status:
  conditions:
    - type: ErrorOccurred
      status: True
      reason: MissingParameter
      message: "error occurred: Template referenced a parameter that doesn't exist" 
      lastTransitionTime: (...)
    - type: ResourcesUpToDate
      status: False
      reason: ErrorOccurred
      message: "A previous error occurred"
      lastTransitionTime:  (...)
  
  
  applications:
    - name: my-app
      condition:
        # Parameter generation was successful...
        - type: ParametersGenerated
          status: True
          reason: ""
          message: ""
          lastTransitionTime: (...)

        # But template rendering failed.
        - type: TemplateRendered
          status: False
          reason: MissingParameter
          message: "Error occurred: Template referenced a parameter that doesn't exist"
          lastTransitionTime: (...)

        # Because template rendering failed, we couldn't apply the resources.
        - type: ResourcesApplied
          status: False
          reason: ""
          message: ""
          lastTransitionTime: (...)

```

This simulates an ApplicationSet with a single Application that with no errors, it sucessfully generated, templated, and applied:
```yaml
status:
  conditions:
    - type: ErrorOccurred
      status: False
      lastTransitionTime: (...)
    - type: ResourcesUpToDate
      status: True 
      lastTransitionTime: (...)
  
  applications:
    - name: my-app
      condition:
        # All Conditions were successful
        - type: ParametersGenerated
          status: True
          lastTransitionTime: (...)
        - type: TemplateRendered
          status: True
          lastTransitionTime: (...)
        - type: ResourcesApplied
          status: true
          lastTransitionTime: (...)

```

And these were the condition types I used above:

condition types for the ApplicationSet as a whole (these are for status.conditions):
- **ErrorOccurred**:  true if an error occurred at any point in the reconciliation, false otherwise.
- **ResourcesUpToDate**:  true if we were successfully able to reconcile, and thus the Applications are fully up-to-date with the ApplicationSet, false otherwise


condition types for individual Applications (these are for status.applications.conditions):
- **ParametersGenerated**: false if error occurred when running the generator, otherwise true (example error: we couldn't connect to the git repository)
- **TemplateRendered**:  false if error occurred when applying parameters to the template, otherwise true (example error: the template referenced a parameter that doesn't exist)
- **ResourcesApplied**: false if we were unable to update/delete the application, otherwise true (example error: the generated application name was too long)

**Comment by mksha** [comment]
may be we can add the list of generated application in the status  field

**Comment by jnpacker** [comment]
I agree with @mksha a condition that the generator was successful, not sure if there is a concern of a long list of clusters.

Some possible conditions:
* Generator complete: True/False
* Labels match NO clusters
* List has a cluster name NOT found in Argo CD
* CustomDecisionResource shows a cluster NOT found in Argo CD

**Comment by jgwest** [comment]
Yah, on the issue of the `.status.applications` field being way too long if you have lots of clusters, agreed. We can probably mitigate that to some degree. But in any case, lets move implementation of that part of this issue to a separate issue, so that it doesn't block adding conditions. I'll handle that.

For your condition examples, would it be possible to instead include those in the `reasons` field?

For example, if  CustomDecisionResource shows a cluster NOT found in Argo CD:
```yaml
status:
  conditions:
    - type: ErrorOccurred
      status: True
      reason: ClusterNotFound # This field is an enum, eg a fixed set of strings that may be used here to communicate various known error states
      # Q: Is there other machine-readable information it would be useful to provide, in addition to the `reason`?
      message: Unable to locate cluster 'cluster-mcclusterface'  # This field is a human readable field, that can be passed back to the user as-is
      lastTransitionTime: (...)
```

This way, we don't necessarily need to have conditions for individual generators. Not that I'm against conditions that are only for individual generators, but it would good to first attempt to make it work generically. 

Finally, as per the Q comment in the yaml above, I'm curious what other additional information it would be beneficial to include :thinking:.
